#!/usr/bin/env python3
"""Regenerate src/<module>.rs from each port crate's src/launch.rs.

The launch logic (grid / block / shared memory / argument packing / host-side control flow) is
copied verbatim. Only these mechanical edits are applied:
  1. `cuda_core::sys` -> `crate::cu` (this crate's libcuda bindings, same names and types).
  2. The module-image loader (embedded cargo-oxide bundle / env var / file read) is replaced by the
     NUL-terminated PTX embedded in this crate (crate::image), returned as &'static [u8].
  3. Every `pub unsafe extern "C" fn` launcher gets `#[unsafe(no_mangle)]`, except the ones listed
     in SKIP (shadowed in the linked mistral.rs binary by another library's definition).
  4. paged-attn-b's `crate::instances` becomes `crate::paged_attn_b::instances` (a child module).
Run: python3 gen.py   (then cargo build; check_symbols.sh verifies the exported set)
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

# port crate -> (module path in this crate, image expression(s))
PORTS = {
    "candle-moe": ("src/candle_moe.rs", "ptx_source", "crate::image::candle_moe()"),
    "mistralrs-core-cuda": ("src/core_cuda.rs", "module_image", "crate::image::core_cuda()"),
    "mistralrs-paged-attn-a": ("src/paged_attn_a.rs", "module_image", "crate::image::paged_attn_a()"),
    "mistralrs-paged-attn-b": ("src/paged_attn_b/mod.rs", "module_image", "crate::image::paged_attn_b()"),
    "mistralrs-quant-a": ("src/quant_a.rs", "module_image", "crate::image::quant_a()"),
    "mistralrs-quant-b": ("src/quant_b.rs", "module_image",
                          "if which == 0 { crate::image::quant_b() } else { crate::image::quant_b_marlin() }"),
    "mistralrs-quant-c": ("src/quant_c.rs", "module_image", "crate::image::quant_c()"),
}

# (port, macro_rules name): launcher macros whose expansions are NOT exported (a duplicate port of
# the same C launchers exists; the one from the port that owns the reference object wins).
SKIP_MACROS = {
    ("mistralrs-quant-b", "bnb_launcher"),  # dequantize_blockwise_* (dequant.o): quant-a's twins are exported
}

# (port, symbol): launchers NOT exported because the linked binary resolves them elsewhere.
SKIP = {
    ("candle-moe", "moe_gemm_wmma"),  # libmistralrscuda.a's moe_gemm_wmma wins -> core_cuda exports it
}

HEADER = "// GENERATED by gen.py from ../{port}/src/launch.rs -- edit the port, then regenerate.\n"


def replace_fn_body(src: str, fname: str, body: str) -> str:
    m = re.search(r"\nfn " + fname + r"\((?P<params>[^)]*)\) -> Vec<u8> \{", src)
    assert m, fname
    i = m.end()
    depth = 1
    while depth:
        c = src[i]
        depth += c == "{"
        depth -= c == "}"
        i += 1
    params = m.group("params")
    new = f"\nfn {fname}({params}) -> &'static [u8] {{\n    {body}\n}}"
    return src[: m.start()] + new + src[i:]


def main():
    for port, (dst, loader, expr) in PORTS.items():
        src = (ROOT / port / "src/launch.rs").read_text()
        n_use = 0
        for a, b in [("use cuda_core::sys as cu;", "use crate::cu;"), ("use cuda_core::sys;", "use crate::cu as sys;")]:
            n_use += src.count(a)
            src = src.replace(a, b)
        assert n_use == 1, (port, n_use)
        src = replace_fn_body(src, loader, expr)
        assert "cuda_core" not in src, port
        if port == "mistralrs-paged-attn-b":
            src = src.replace("crate::instances", "crate::paged_attn_b::instances") + "\npub mod instances;\n"

        def add_attr(m):
            indent, name = m.group(1), m.group(2)
            if (port, name) in SKIP:
                return f"{indent}#[allow(dead_code)]\n{indent}pub unsafe extern \"C\" fn {name}"
            return f"{indent}#[unsafe(no_mangle)]\n{indent}pub unsafe extern \"C\" fn {name}"

        src, n = re.subn(r"(?m)^([ \t]*)pub unsafe extern \"C\" fn ([A-Za-z_$][A-Za-z_0-9]*)", add_attr, src)
        for (p, mac) in SKIP_MACROS:
            if p != port:
                continue
            a = src.index(f"macro_rules! {mac} {{")
            b = src.index("\n}", a)
            body = src[a:b].replace("#[unsafe(no_mangle)]", "#[allow(dead_code)]")
            assert body != src[a:b], mac
            src = src[:a] + body + src[b:]
        out = HERE / dst
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(HEADER.format(port=port) + src)
        print(f"{port:24} -> {dst:26} {n} launcher definitions")
    inst = (ROOT / "mistralrs-paged-attn-b/src/instances.rs").read_text()
    (HERE / "src/paged_attn_b/instances.rs").write_text(HEADER.format(port="mistralrs-paged-attn-b").replace("launch.rs", "instances.rs") + inst)


if __name__ == "__main__":
    main()
