// GENERATED by gen.py from ../candle-moe/src/launch.rs -- edit the port, then regenerate.
//! Pure-Rust host launchers with the exact `candle-kernels/src/ffi.rs` signatures of candle's MoE C
//! launchers (`moe_gemm_wmma`, `moe_gemm_gguf`, `moe_gemm_gguf_prefill`), launching the cuda-oxide
//! kernels of this crate on the caller's stream through the CUDA driver API.
//!
//! Reproduced host logic (moe_wmma.cu / moe_gguf.cu / moe_wmma_gguf.cu / moe_utils.cuh):
//! - offsets: memset(counts) -> count_tokens_per_expert (grid ceil(m/256), block 256) -> scan.
//!   The reference scans with thrust::inclusive_scan (prefill) or `expert_prefix_sum_kernel`
//!   (decode, one block of max(num_experts, 32) <= 1024 threads); both are replaced by
//!   `moe_expert_offsets` (same integers). A decode launch with num_experts > 1024 is an invalid
//!   CUDA launch in the reference (offsets left untouched); mirrored by skipping the scan.
//! - `moe_gemm_gguf`: cudaMallocAsync'd Q8_1 buffer (m = topk_weights ? size_m : size_m / topk rows
//!   of pad(k, 512)), quantize_q8_1 grid (ceil(kx_padded/256), m), GEMV grid (ceil(n/4), size_m),
//!   block (32, 4), shared size_k/qk*sizeof(block)*4 + 1024, then cudaFreeAsync.
//! - `moe_gemm_gguf_prefill`: cudaMallocAsync'd counts/offsets, the thrust-path offsets, grid
//!   (num_experts, ceil(n/32)), block (32|64, 4), shared A + B + Bq + C, then cudaFreeAsync.
//! - The reference objects are compiled with `--default-stream per-thread`: stream 0 means the
//!   per-thread default stream (`CU_STREAM_PER_THREAD`), not the legacy stream.
//! - A launch with a zero grid dimension fails in the reference and does nothing; skipped here.
//!
//! The oxide PTX is loaded once per CUDA context (embedded bundle of this executable, else
//! `$CANDLE_MOE_PTX`, else `candle_moe.ptx` next to Cargo.toml).
use crate::cu;
use std::collections::HashMap;
use std::ffi::c_void;
use std::sync::Mutex;

const CU_STREAM_PER_THREAD: usize = 0x2;

struct Module {
    module: cu::CUmodule,
    funcs: HashMap<&'static str, cu::CUfunction>,
}
unsafe impl Send for Module {}

static MODULES: Mutex<Option<HashMap<usize, Module>>> = Mutex::new(None);

fn ptx_source() -> &'static [u8] {
    crate::image::candle_moe()
}

fn check(r: cu::CUresult, what: &str) {
    if r != cu::cudaError_enum_CUDA_SUCCESS {
        panic!("candle-moe: {what} failed: {r:?}");
    }
}

fn cu_stream(stream: i64) -> cu::CUstream {
    if stream == 0 { CU_STREAM_PER_THREAD as cu::CUstream } else { stream as usize as cu::CUstream }
}

/// The function `name` in this crate's module for the context owning `stream`.
unsafe fn function(stream: cu::CUstream, name: &'static str) -> cu::CUfunction {
    let mut ctx: cu::CUcontext = std::ptr::null_mut();
    if stream as usize != CU_STREAM_PER_THREAD {
        check(cu::cuStreamGetCtx(stream, &mut ctx), "cuStreamGetCtx");
    }
    if ctx.is_null() {
        check(cu::cuCtxGetCurrent(&mut ctx), "cuCtxGetCurrent");
    }
    let mut guard = MODULES.lock().unwrap();
    let map = guard.get_or_insert_with(HashMap::new);
    let m = map.entry(ctx as usize).or_insert_with(|| {
        let src = ptx_source();
        let mut module: cu::CUmodule = std::ptr::null_mut();
        check(cu::cuCtxPushCurrent_v2(ctx), "cuCtxPushCurrent");
        check(cu::cuModuleLoadData(&mut module, src.as_ptr() as *const c_void), "cuModuleLoadData(candle-moe PTX)");
        let mut popped: cu::CUcontext = std::ptr::null_mut();
        check(cu::cuCtxPopCurrent_v2(&mut popped), "cuCtxPopCurrent");
        Module { module, funcs: HashMap::new() }
    });
    let module = m.module;
    *m.funcs.entry(name).or_insert_with(|| {
        let mut f: cu::CUfunction = std::ptr::null_mut();
        let cname = std::ffi::CString::new(name).unwrap();
        check(cu::cuModuleGetFunction(&mut f, module, cname.as_ptr()), name);
        f
    })
}

/// A kernel argument list: each value is stored in its own 8-byte slot.
struct Args(Vec<[u8; 8]>);
impl Args {
    fn new() -> Self {
        Args(Vec::new())
    }
    fn p<T>(mut self, v: *const T) -> Self {
        self.0.push((v as u64).to_le_bytes());
        self
    }
    fn i(mut self, v: i32) -> Self {
        self.0.push((v as u32 as u64).to_le_bytes());
        self
    }
}

unsafe fn launch(stream: cu::CUstream, name: &'static str, grid: (u32, u32, u32), block: (u32, u32, u32), shared: u32, args: Args) {
    if grid.0 == 0 || grid.1 == 0 || grid.2 == 0 {
        return; // the reference's launch fails with cudaErrorInvalidConfiguration: nothing runs
    }
    let f = function(stream, name);
    let mut slots = args.0;
    let mut ptrs: Vec<*mut c_void> = slots.iter_mut().map(|s| s.as_mut_ptr() as *mut c_void).collect();
    check(
        cu::cuLaunchKernel(f, grid.0, grid.1, grid.2, block.0, block.1, block.2, shared, stream, ptrs.as_mut_ptr(), std::ptr::null_mut()),
        name,
    );
}

unsafe fn memset0(stream: cu::CUstream, p: *mut i32, count: usize) {
    if count > 0 {
        check(cu::cuMemsetD32Async(p as u64, 0, count, stream), "cuMemsetD32Async");
    }
}

/// count_tokens_per_expert + exclusive scan into offsets[0..=num_experts]; `light` is the decode
/// path (`calculate_expert_offsets_light`).
unsafe fn compute_offsets(stream: cu::CUstream, expert_ids: *const i32, size_m: i32, counts: *mut i32, offsets: *mut i32, num_experts: i32, light: bool) {
    memset0(stream, counts, num_experts.max(0) as usize);
    let blocks = (size_m + 255) / 256;
    launch(stream, "moe_count_tokens", (blocks.max(0) as u32, 1, 1), (256, 1, 1), 0,
           Args::new().p(expert_ids).p(counts).i(size_m));
    if light && num_experts > 1024 {
        return; // expert_prefix_sum_kernel<<<1, num_experts>>> is an invalid launch
    }
    if num_experts <= 0 {
        if !light && num_experts == 0 {
            // thrust scans nothing; offsets[0] = 0 by the memset
            memset0(stream, offsets, 1);
        }
        return;
    }
    launch(stream, "moe_expert_offsets", (1, 1, 1), (1024, 1, 1), 0, Args::new().p(counts).p(offsets).i(num_experts));
}

/// `moe_gemm_wmma` (moe_wmma.cu).
#[allow(clippy::too_many_arguments)]
#[allow(dead_code)]
pub unsafe extern "C" fn moe_gemm_wmma(
    input: *const c_void,
    weights: *const c_void,
    sorted_token_ids: *const i32,
    expert_ids: *const i32,
    topk_weights: *const f32,
    output: *mut c_void,
    expert_counts: *mut i32,
    expert_offsets: *mut i32,
    num_experts: i32,
    topk: i32,
    size_m: i32,
    size_n: i32,
    size_k: i32,
    dtype: i32,
    is_prefill: bool,
    stream: i64,
) {
    let s = cu_stream(stream);
    compute_offsets(s, expert_ids, size_m, expert_counts, expert_offsets, num_experts, !is_prefill);
    let grid = (num_experts as u32, ((size_n + 31) / 32) as u32, 1);
    // A_sh 1024 + B_sh 1024 (+ pad 0) + C_sh 4096
    let smem = 1024 + 1024 + 32 * 32 * 4;
    let name = match (dtype, is_prefill) {
        (0, true) => "moe_wmma_f16_prefill",
        (0, false) => "moe_wmma_f16_decode",
        (1, true) => "moe_wmma_bf16_prefill",
        (1, false) => "moe_wmma_bf16_decode",
        _ => return,
    };
    launch(s, name, grid, (128, 1, 1), smem,
           Args::new().p(input).p(weights).p(sorted_token_ids).p(expert_offsets).p(topk_weights).p(output)
               .i(num_experts).i(topk).i(size_m).i(size_n).i(size_k));
}

/// (qk, sizeof(block)) for gguf types 0..5.
fn gguf_block(t: i32) -> Option<(i32, i32)> {
    Some(match t {
        0 => (32, 34),
        1 => (256, 144),
        2 => (256, 84),
        3 => (256, 110),
        4 => (256, 176),
        5 => (256, 210),
        _ => return None,
    })
}

/// `moe_gemm_gguf` (moe_gguf.cu), decode.
#[allow(clippy::too_many_arguments)]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn moe_gemm_gguf(
    input: *const f32,
    weights: *const c_void,
    sorted_token_ids: *const i32,
    expert_ids: *const i32,
    topk_weights: *const f32,
    output: *mut c_void,
    num_experts: i32,
    topk: i32,
    size_m: i32,
    size_n: i32,
    size_k: i32,
    gguf_dtype: i32,
    stream: i64,
) {
    let s = cu_stream(stream);
    let kx_padded = (size_k + 511) / 512 * 512;
    let num_blocks = (kx_padded + 255) / 256;
    let m = if topk_weights.is_null() { size_m / topk } else { size_m };
    let y_bytes = m.wrapping_mul(kx_padded / 32 * 36);
    let mut y: cu::CUdeviceptr = 0;
    if y_bytes > 0 {
        check(cu::cuMemAllocAsync(&mut y, y_bytes as i64 as u64 as usize, s), "cuMemAllocAsync");
    }
    launch(s, "moe_quantize_q8_1", (num_blocks as u32, m as u32, 1), (256, 1, 1), 0,
           Args::new().p(input).p(y as *const u8).i(size_k).i(kx_padded));
    if let Some((qk, bs)) = gguf_block(gguf_dtype) {
        let n_wraps = 4;
        let shared = size_k / qk * bs * n_wraps + 1024;
        let name = ["moe_gguf_q8_0", "moe_gguf_q4_k", "moe_gguf_q2_k", "moe_gguf_q3_k", "moe_gguf_q5_k", "moe_gguf_q6_k"][gguf_dtype as usize];
        launch(s, name, (((size_n + n_wraps - 1) / n_wraps) as u32, size_m as u32, 1), (32, n_wraps as u32, 1), shared as u32,
               Args::new().p(weights).p(y as *const u8).p(sorted_token_ids).p(expert_ids).p(topk_weights).p(output)
                   .i(num_experts).i(topk).i(size_m).i(size_n).i(size_k).i(kx_padded));
    }
    if y != 0 {
        check(cu::cuMemFreeAsync(y, s), "cuMemFreeAsync");
    }
}

/// `moe_gemm_gguf_prefill` (moe_wmma_gguf.cu).
#[allow(clippy::too_many_arguments)]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn moe_gemm_gguf_prefill(
    input: *const c_void,
    weights: *const u8,
    sorted_token_ids: *const i32,
    expert_ids: *const i32,
    topk_weights: *const f32,
    output: *mut c_void,
    num_experts: i32,
    topk: i32,
    size_m: i32,
    size_n: i32,
    size_k: i32,
    input_dtype: i32,
    gguf_dtype: i32,
    stream: i64,
) {
    let s = cu_stream(stream);
    let mut counts: cu::CUdeviceptr = 0;
    let mut offsets: cu::CUdeviceptr = 0;
    let ne = num_experts.max(0) as usize;
    if ne > 0 {
        check(cu::cuMemAllocAsync(&mut counts, ne * 4, s), "cuMemAllocAsync");
    }
    check(cu::cuMemAllocAsync(&mut offsets, (ne + 1) * 4, s), "cuMemAllocAsync");
    compute_offsets(s, expert_ids, size_m, counts as *mut i32, offsets as *mut i32, num_experts, false);
    if let Some((qk, bs)) = gguf_block(gguf_dtype) {
        let a = 32 * qk * 2;
        let smem = (2 * a + 32 * bs + 3) / 4 * 4 + 32 * 32 * 4;
        let wrap = if gguf_dtype == 0 || gguf_dtype == 1 { 32 } else { 64 };
        let tn = ["q8_0", "q4_k", "q2_k", "q3_k", "q5_k", "q6_k"][gguf_dtype as usize];
        let name: &'static str = match (input_dtype == 0, tn) {
            (true, "q8_0") => "moe_gguf_prefill_f16_q8_0",
            (true, "q4_k") => "moe_gguf_prefill_f16_q4_k",
            (true, "q2_k") => "moe_gguf_prefill_f16_q2_k",
            (true, "q3_k") => "moe_gguf_prefill_f16_q3_k",
            (true, "q5_k") => "moe_gguf_prefill_f16_q5_k",
            (true, _) => "moe_gguf_prefill_f16_q6_k",
            (false, "q8_0") => "moe_gguf_prefill_bf16_q8_0",
            (false, "q4_k") => "moe_gguf_prefill_bf16_q4_k",
            (false, "q2_k") => "moe_gguf_prefill_bf16_q2_k",
            (false, "q3_k") => "moe_gguf_prefill_bf16_q3_k",
            (false, "q5_k") => "moe_gguf_prefill_bf16_q5_k",
            (false, _) => "moe_gguf_prefill_bf16_q6_k",
        };
        launch(s, name, (num_experts as u32, ((size_n + 31) / 32) as u32, 1), (wrap, 4, 1), smem as u32,
               Args::new().p(input).p(weights).p(sorted_token_ids).p(offsets as *const i32).p(topk_weights).p(output)
                   .i(num_experts).i(topk).i(size_m).i(size_n).i(size_k));
    }
    if counts != 0 {
        check(cu::cuMemFreeAsync(counts, s), "cuMemFreeAsync");
    }
    check(cu::cuMemFreeAsync(offsets, s), "cuMemFreeAsync");
}
