// GENERATED by gen.py from ../mistralrs-core-cuda/src/launch.rs -- edit the port, then regenerate.
//! Pure-Rust twins of the extern "C" host launchers of mistralrs-core's CUDA library
//! (libmistralrscuda.a): same names, same parameter lists and C ABI as the declarations in
//! mistralrs-core/src/cuda/ffi.rs, same grid / block / shared-memory selection and host-side
//! control flow, launching the oxide kernels of this crate on the caller's stream through the
//! CUDA driver API.
//!
//! - The reference objects are compiled with `--default-stream per-thread` (`_ptsz` runtime
//!   symbols): stream 0 means the per-thread default stream (`CU_STREAM_PER_THREAD`).
//! - The oxide module is loaded once per CUDA context (the stream's context, or the current one for
//!   stream 0; if no context is current, device 0's primary context, as the runtime API would) and
//!   its functions are cached. The module image is the `#[cuda_module]` bundle embedded in the
//!   running executable; if there is none, `$MISTRALRS_CORE_CUDA_PTX`, else
//!   `<crate>/mistralrs_core_cuda.ptx`.
//! - Like the C launchers (`<<<>>>` without error checks), launch failures are dropped. A launch
//!   with a zero grid dimension is an invalid configuration in the reference: skipped here.
#![allow(clippy::missing_safety_doc, clippy::too_many_arguments)]
use crate::cu as sys;
use std::collections::HashMap;
use std::ffi::{CString, c_void};
use std::sync::{Mutex, OnceLock};

const CU_STREAM_PER_THREAD: usize = 0x2;

struct Module {
    module: sys::CUmodule,
    functions: HashMap<&'static str, sys::CUfunction>,
}
// CUmodule / CUfunction are driver handles, valid from any thread of the process.
unsafe impl Send for Module {}

static MODULES: OnceLock<Mutex<HashMap<usize, Module>>> = OnceLock::new();

fn module_image() -> &'static [u8] {
    crate::image::core_cuda()
}

fn check(r: sys::CUresult, what: &str) {
    assert!(r == 0, "mistralrs-core-cuda: {what} failed: {r:?}");
}

fn cu_stream(stream: i64) -> sys::CUstream {
    if stream == 0 { CU_STREAM_PER_THREAD as sys::CUstream } else { stream as usize as sys::CUstream }
}

/// The context `stream` belongs to (the current context for the per-thread default stream).
unsafe fn stream_context(stream: sys::CUstream) -> sys::CUcontext {
    unsafe {
        check(sys::cuInit(0), "cuInit");
        let mut ctx: sys::CUcontext = std::ptr::null_mut();
        if stream as usize != CU_STREAM_PER_THREAD && !stream.is_null() {
            check(sys::cuStreamGetCtx(stream, &mut ctx), "cuStreamGetCtx");
            return ctx;
        }
        check(sys::cuCtxGetCurrent(&mut ctx), "cuCtxGetCurrent");
        if ctx.is_null() {
            let mut dev: sys::CUdevice = 0;
            check(sys::cuDeviceGet(&mut dev, 0), "cuDeviceGet");
            check(sys::cuDevicePrimaryCtxRetain(&mut ctx, dev), "cuDevicePrimaryCtxRetain");
            check(sys::cuCtxSetCurrent(ctx), "cuCtxSetCurrent");
        }
        ctx
    }
}

/// The oxide kernel `name` in `stream`'s context (loading the module on first use).
unsafe fn function(name: &'static str, stream: sys::CUstream) -> sys::CUfunction {
    unsafe {
        let ctx = stream_context(stream);
        let mut map = MODULES.get_or_init(|| Mutex::new(HashMap::new())).lock().unwrap();
        let m = map.entry(ctx as usize).or_insert_with(|| {
            let mut cur: sys::CUcontext = std::ptr::null_mut();
            check(sys::cuCtxGetCurrent(&mut cur), "cuCtxGetCurrent");
            if cur != ctx {
                check(sys::cuCtxPushCurrent_v2(ctx), "cuCtxPushCurrent");
            }
            let image = module_image();
            let mut module: sys::CUmodule = std::ptr::null_mut();
            check(sys::cuModuleLoadData(&mut module, image.as_ptr() as *const c_void), "cuModuleLoadData");
            if cur != ctx {
                let mut popped: sys::CUcontext = std::ptr::null_mut();
                check(sys::cuCtxPopCurrent_v2(&mut popped), "cuCtxPopCurrent");
            }
            Module { module, functions: HashMap::new() }
        });
        let module = m.module;
        *m.functions.entry(name).or_insert_with(|| {
            let mut f: sys::CUfunction = std::ptr::null_mut();
            let c = CString::new(name).unwrap();
            check(sys::cuModuleGetFunction(&mut f, module, c.as_ptr()), name);
            f
        })
    }
}

static LAUNCHED: OnceLock<Mutex<std::collections::HashSet<&'static str>>> = OnceLock::new();

/// Names of the oxide kernels launched so far by this process (gate coverage).
pub fn launched_kernels() -> Vec<&'static str> {
    LAUNCHED.get_or_init(|| Mutex::new(std::collections::HashSet::new())).lock().unwrap().iter().copied().collect()
}

/// Launch `name` (grid dims as the C `dim3` holds them: unsigned int).
unsafe fn launch(name: &'static str, grid: (u32, u32, u32), block: (u32, u32, u32), smem: u32, stream: sys::CUstream, args: &mut [*mut c_void]) {
    if grid.0 == 0 || grid.1 == 0 || grid.2 == 0 {
        return;
    }
    LAUNCHED.get_or_init(|| Mutex::new(std::collections::HashSet::new())).lock().unwrap().insert(name);
    unsafe {
        let f = function(name, stream);
        let _ = sys::cuLaunchKernel(f, grid.0, grid.1, grid.2, block.0, block.1, block.2, smem, stream, args.as_mut_ptr(), std::ptr::null_mut());
    }
}

/// `cudaFuncSetAttribute(kernel, cudaFuncAttributeMaxDynamicSharedMemorySize, bytes)`.
unsafe fn set_max_dynamic_smem(name: &'static str, stream: sys::CUstream, bytes: i32) {
    unsafe {
        let f = function(name, stream);
        let _ = sys::cuFuncSetAttribute(f, sys::CUfunction_attribute_enum_CU_FUNC_ATTRIBUTE_MAX_DYNAMIC_SHARED_SIZE_BYTES, bytes);
    }
}

/// Pointers to each argument, in order, for `cuLaunchKernel`.
macro_rules! args {
    ($($a:expr),* $(,)?) => { [$( &raw mut $a as *mut c_void ),*] };
}

// ================================================================================================
// graph.cu

#[unsafe(no_mangle)]
pub unsafe extern "C" fn cuda_graph_copy_bytes(src: *const c_void, dst: *mut c_void, n: i64, stream: i64) -> i32 {
    if n < 0 {
        return 1;
    }
    if n == 0 {
        return 0;
    }
    unsafe {
        let s = cu_stream(stream);
        stream_context(s);
        sys::cuMemcpyAsync(dst as sys::CUdeviceptr, src as sys::CUdeviceptr, n as usize, s) as i32
    }
}

/// v0.9.4 `cuda_graph_copy_2d_bytes`: `cudaMemcpy2DAsync` device to device (`cuMemcpy2DAsync`).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn cuda_graph_copy_2d_bytes(
    src: *const c_void, dst: *mut c_void, width: i64, height: i64, src_pitch: i64, dst_pitch: i64, stream: i64,
) -> i32 {
    if width < 0 || height < 0 || src_pitch < width || dst_pitch < width {
        return 1;
    }
    if width == 0 || height == 0 {
        return 0;
    }
    unsafe {
        let s = cu_stream(stream);
        stream_context(s);
        let mut p: sys::CUDA_MEMCPY2D = std::mem::zeroed();
        p.srcMemoryType = sys::CUmemorytype_enum_CU_MEMORYTYPE_DEVICE;
        p.srcDevice = src as sys::CUdeviceptr;
        p.srcPitch = src_pitch as usize;
        p.dstMemoryType = sys::CUmemorytype_enum_CU_MEMORYTYPE_DEVICE;
        p.dstDevice = dst as sys::CUdeviceptr;
        p.dstPitch = dst_pitch as usize;
        p.WidthInBytes = width as usize;
        p.Height = height as usize;
        sys::cuMemcpy2DAsync_v2(&p, s) as i32
    }
}

// ================================================================================================
// input_packing.cu (v0.9.4)

/// Launch `name` and return what the runtime's `cudaGetLastError()` would after it (0 = launched).
unsafe fn launch_status(name: &'static str, grid: (u32, u32, u32), block: (u32, u32, u32), stream: sys::CUstream, args: &mut [*mut c_void]) -> i32 {
    if grid.0 == 0 || grid.1 == 0 || grid.2 == 0 {
        return 9; // cudaErrorInvalidConfiguration
    }
    LAUNCHED.get_or_init(|| Mutex::new(std::collections::HashSet::new())).lock().unwrap().insert(name);
    unsafe {
        let f = function(name, stream);
        sys::cuLaunchKernel(f, grid.0, grid.1, grid.2, block.0, block.1, block.2, 0, stream, args.as_mut_ptr(), std::ptr::null_mut()) as i32
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pad_decode_input_u32(input: *const c_void, output: *mut c_void, input_rows: i32, output_rows: i32, width: i32, stream: i64) -> i32 {
    if input.is_null() || output.is_null() || input_rows <= 0 || output_rows < input_rows || width <= 0 {
        return 1; // cudaErrorInvalidValue
    }
    const THREADS: i64 = 256;
    let elements = (output_rows as i64) * (width as i64);
    let blocks = ((elements + THREADS - 1) / THREADS) as i32;
    let (mut i, mut o, mut ir, mut or, mut w) = (input, output, input_rows, output_rows, width);
    unsafe { launch_status("pad_decode_input_kernel", (blocks as u32, 1, 1), (THREADS as u32, 1, 1), cu_stream(stream), &mut args![i, o, ir, or, w]) }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn pack_completion_input_u32(
    host: *const c_void, staged_rows: *const *const c_void, output: *mut c_void, rows: i32, host_width: i32, staged_width: i32, stream: i64,
) -> i32 {
    if host.is_null() || staged_rows.is_null() || output.is_null() || rows <= 0 || host_width <= 0 || staged_width <= 0 {
        return 1;
    }
    const ROWS_PER_LAUNCH: i32 = 64;
    const THREADS: i64 = 256;
    let s = cu_stream(stream);
    let mut row_start = 0i32;
    while row_start < rows {
        let chunk_rows = (rows - row_start).min(ROWS_PER_LAUNCH);
        let mut packed = [0u64; 64];
        for r in 0..chunk_rows as usize {
            packed[r] = unsafe { *staged_rows.add(row_start as usize + r) } as u64;
        }
        let row_width = (host_width as i64) + (staged_width as i64);
        let elements = (chunk_rows as i64) * row_width;
        let blocks = ((elements + THREADS - 1) / THREADS) as i32;
        let mut h = unsafe { (host as *const u32).offset((row_start as i64 * host_width as i64) as isize) } as u64;
        let mut o = unsafe { (output as *mut u32).offset((row_start as i64 * row_width) as isize) } as u64;
        let (mut cr, mut hw, mut sw) = (chunk_rows, host_width, staged_width);
        let mut a: Vec<*mut c_void> = Vec::with_capacity(68);
        a.push(&raw mut h as *mut c_void);
        for p in packed.iter_mut() {
            a.push(p as *mut u64 as *mut c_void);
        }
        a.push(&raw mut o as *mut c_void);
        a.push(&raw mut cr as *mut c_void);
        a.push(&raw mut hw as *mut c_void);
        a.push(&raw mut sw as *mut c_void);
        let st = unsafe { launch_status("pack_completion_input_kernel", (blocks as u32, 1, 1), (THREADS as u32, 1, 1), s, &mut a) };
        if st != 0 {
            return st;
        }
        row_start += ROWS_PER_LAUNCH;
    }
    0
}

// ================================================================================================
// gdn.cu

const GDR_TILED_64: &str = "_Z40gated_delta_rule_recurrence_kernel_tiledILi64ELi64EEvPKfS1_S1_S1_S1_PfS2_ii";
const GDR_TILED_128: &str = "_Z40gated_delta_rule_recurrence_kernel_tiledILi128ELi64EEvPKfS1_S1_S1_S1_PfS2_ii";
const GDR_FALLBACK: &str = "_Z43gated_delta_rule_recurrence_kernel_fallbackILi64ELi256EEvPKfS1_S1_S1_S1_PfS2_iii";
const GDR_WARP_64: &str = "_Z39gated_delta_rule_recurrence_kernel_warpILi64ELi4EEvPKfS1_S1_S1_S1_PfS2_ii";
const GDR_WARP_128: &str = "_Z39gated_delta_rule_recurrence_kernel_warpILi128ELi4EEvPKfS1_S1_S1_S1_PfS2_ii";
const GDR_CHUNKED_64: &str = "_Z31chunked_gated_delta_rule_kernelILi64ELi64ELi64EEvPKfS1_S1_S1_S1_PfS2_ii";
const GDR_CHUNKED_128: &str = "_Z31chunked_gated_delta_rule_kernelILi64ELi128ELi64EEvPKfS1_S1_S1_S1_PfS2_ii";

fn cdiv_u(a: i32, b: i32) -> u32 {
    (a.wrapping_add(b - 1) / b) as u32
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn gated_delta_rule_recurrence(
    q: *const f32, k: *const f32, v: *const f32, g: *const f32, beta: *const f32, state: *mut f32, output: *mut f32, bh: i32,
    seq_len: i32, k_dim: i32, v_dim: i32, stream: i64,
) {
    let s = cu_stream(stream);
    let (mut q, mut k, mut v, mut g, mut beta, mut state, mut output, mut seq_len, mut k_dim, mut v_dim) =
        (q, k, v, g, beta, state, output, seq_len, k_dim, v_dim);
    let grid = (cdiv_u(v_dim, 64), bh as u32, 1);
    unsafe {
        if k_dim == 128 || k_dim == 64 {
            let name = if k_dim == 128 { GDR_TILED_128 } else { GDR_TILED_64 };
            launch(name, grid, (64, 1, 1), 0, s, &mut args!(q, k, v, g, beta, state, output, seq_len, v_dim));
        } else {
            let smem = (2 * k_dim as i64 * 4) as u32;
            launch(GDR_FALLBACK, grid, (64, 1, 1), smem, s, &mut args!(q, k, v, g, beta, state, output, seq_len, k_dim, v_dim));
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn warp_gated_delta_rule_recurrence(
    q: *const f32, k: *const f32, v: *const f32, g: *const f32, beta: *const f32, state: *mut f32, output: *mut f32, bh: i32,
    seq_len: i32, k_dim: i32, v_dim: i32, stream: i64,
) {
    if k_dim != 128 && k_dim != 64 {
        return unsafe { gated_delta_rule_recurrence(q, k, v, g, beta, state, output, bh, seq_len, k_dim, v_dim, stream) };
    }
    let s = cu_stream(stream);
    let (mut q, mut k, mut v, mut g, mut beta, mut state, mut output, mut seq_len, mut v_dim) = (q, k, v, g, beta, state, output, seq_len, v_dim);
    let grid = (cdiv_u(v_dim, 4), bh as u32, 1);
    let name = if k_dim == 128 { GDR_WARP_128 } else { GDR_WARP_64 };
    unsafe { launch(name, grid, (32, 4, 1), 0, s, &mut args!(q, k, v, g, beta, state, output, seq_len, v_dim)) };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn chunked_gated_delta_rule_recurrence(
    q: *const f32, k: *const f32, v: *const f32, g: *const f32, beta: *const f32, state: *mut f32, output: *mut f32, bh: i32,
    seq_len: i32, k_dim: i32, v_dim: i32, stream: i64,
) {
    if k_dim != 128 && k_dim != 64 {
        return unsafe { gated_delta_rule_recurrence(q, k, v, g, beta, state, output, bh, seq_len, k_dim, v_dim, stream) };
    }
    let s = cu_stream(stream);
    let (mut q, mut k, mut v, mut g, mut beta, mut state, mut output, mut seq_len, mut v_dim) = (q, k, v, g, beta, state, output, seq_len, v_dim);
    let (bt, bk) = (64, k_dim);
    let smem = (bt * bk + bt * bt + 2 * bt + bk) * 4;
    let name = if k_dim == 128 { GDR_CHUNKED_128 } else { GDR_CHUNKED_64 };
    unsafe {
        set_max_dynamic_smem(name, s, smem);
        launch(name, (cdiv_u(v_dim, 64), bh as u32, 1), (64, 1, 1), smem as u32, s, &mut args!(q, k, v, g, beta, state, output, seq_len, v_dim));
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn causal_conv1d_update(
    x: *const c_void, weight: *const c_void, conv_state: *mut c_void, output: *mut c_void, batch_size: i32, conv_dim: i32,
    kernel_size: i32, dtype: i32, stream: i64,
) {
    let s = cu_stream(stream);
    let (mut x, mut weight, mut conv_state, mut output, mut batch_size, mut conv_dim, mut kernel_size) =
        (x, weight, conv_state, output, batch_size, conv_dim, kernel_size);
    let name = if dtype == 0 {
        "_Z27causal_conv1d_update_kernelI6__halfEvPKT_S3_PS1_S4_iii"
    } else {
        "_Z27causal_conv1d_update_kernelI13__nv_bfloat16EvPKT_S3_PS1_S4_iii"
    };
    unsafe {
        launch(name, (cdiv_u(conv_dim, 256), batch_size as u32, 1), (256, 1, 1), 0, s, &mut args!(x, weight, conv_state, output, batch_size, conv_dim, kernel_size))
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn causal_conv1d_full(
    x: *const c_void, weight: *const c_void, conv_state_out: *mut c_void, output: *mut c_void, batch_size: i32, conv_dim: i32,
    seq_len: i32, kernel_size: i32, dtype: i32, stream: i64,
) {
    let s = cu_stream(stream);
    let (mut x, mut weight, mut cs, mut output, mut batch_size, mut conv_dim, mut seq_len, mut kernel_size) =
        (x, weight, conv_state_out, output, batch_size, conv_dim, seq_len, kernel_size);
    let (full, save) = if dtype == 0 {
        ("_Z25causal_conv1d_full_kernelI6__halfEvPKT_S3_PS1_iiii", "_Z22save_conv_state_kernelI6__halfEvPKT_PS1_iiii")
    } else {
        ("_Z25causal_conv1d_full_kernelI13__nv_bfloat16EvPKT_S3_PS1_iiii", "_Z22save_conv_state_kernelI13__nv_bfloat16EvPKT_PS1_iiii")
    };
    unsafe {
        launch(full, (cdiv_u(conv_dim, 256), seq_len as u32, batch_size as u32), (256, 1, 1), 0, s,
               &mut args!(x, weight, output, batch_size, conv_dim, seq_len, kernel_size));
        launch(save, (cdiv_u(conv_dim, 256), batch_size as u32, 1), (256, 1, 1), 0, s,
               &mut args!(x, cs, batch_size, conv_dim, seq_len, kernel_size));
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn gdn_prepare_recurrence(
    mixed_qkv: *const c_void, b: *const c_void, a: *const c_void, a_log: *const f32, dt_bias: *const f32, q_out: *mut f32,
    k_out: *mut f32, v_out: *mut f32, g_out: *mut f32, beta_out: *mut f32, batch_size: i32, seq_len: i32, num_k_heads: i32,
    num_v_heads: i32, head_k_dim: i32, head_v_dim: i32, dtype: i32, stream: i64,
) {
    let s = cu_stream(stream);
    let grid = batch_size.wrapping_mul(seq_len).wrapping_mul(num_v_heads) as u32;
    let (mut m, mut b, mut a, mut al, mut db, mut qo, mut ko, mut vo, mut go, mut bo) = (mixed_qkv, b, a, a_log, dt_bias, q_out, k_out, v_out, g_out, beta_out);
    let (mut bs, mut sl, mut nk, mut nv, mut hk, mut hv) = (batch_size, seq_len, num_k_heads, num_v_heads, head_k_dim, head_v_dim);
    let name = if dtype == 0 {
        "_Z29gdn_prepare_recurrence_kernelI6__halfEvPKT_S3_S3_PKfS5_PfS6_S6_S6_S6_iiiiii"
    } else {
        "_Z29gdn_prepare_recurrence_kernelI13__nv_bfloat16EvPKT_S3_S3_PKfS5_PfS6_S6_S6_S6_iiiiii"
    };
    unsafe { launch(name, (grid, 1, 1), (256, 1, 1), 0, s, &mut args!(m, b, a, al, db, qo, ko, vo, go, bo, bs, sl, nk, nv, hk, hv)) };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn gdn_decode_recurrence(
    mixed_qkv: *const c_void, b: *const c_void, a: *const c_void, a_log: *const f32, dt_bias: *const f32, state: *mut f32,
    output: *mut f32, batch_size: i32, num_k_heads: i32, num_v_heads: i32, head_k_dim: i32, head_v_dim: i32, dtype: i32, stream: i64,
) {
    let s = cu_stream(stream);
    let grid = (cdiv_u(head_v_dim, 64), batch_size.wrapping_mul(num_v_heads) as u32, 1);
    let (mut m, mut b, mut a, mut al, mut db, mut st, mut out) = (mixed_qkv, b, a, a_log, dt_bias, state, output);
    let (mut bs, mut nk, mut nv, mut hk, mut hv) = (batch_size, num_k_heads, num_v_heads, head_k_dim, head_v_dim);
    unsafe {
        if head_k_dim == 128 || head_k_dim == 64 {
            let name = match (head_k_dim, dtype == 0) {
                (128, true) => "_Z28gdn_decode_recurrence_kernelI6__halfLi128ELi64EEvPKT_S3_S3_PKfS5_PfS6_iiii",
                (128, false) => "_Z28gdn_decode_recurrence_kernelI13__nv_bfloat16Li128ELi64EEvPKT_S3_S3_PKfS5_PfS6_iiii",
                (_, true) => "_Z28gdn_decode_recurrence_kernelI6__halfLi64ELi64EEvPKT_S3_S3_PKfS5_PfS6_iiii",
                (_, false) => "_Z28gdn_decode_recurrence_kernelI13__nv_bfloat16Li64ELi64EEvPKT_S3_S3_PKfS5_PfS6_iiii",
            };
            launch(name, grid, (64, 1, 1), 0, s, &mut args!(m, b, a, al, db, st, out, bs, nk, nv, hv));
        } else {
            let smem = ((2 * 64 + 2 * head_k_dim as i64) * 4) as u32;
            let name = if dtype == 0 {
                "_Z37gdn_decode_recurrence_kernel_fallbackI6__halfLi64ELi256EEvPKT_S3_S3_PKfS5_PfS6_iiiii"
            } else {
                "_Z37gdn_decode_recurrence_kernel_fallbackI13__nv_bfloat16Li64ELi256EEvPKT_S3_S3_PKfS5_PfS6_iiiii"
            };
            launch(name, grid, (64, 1, 1), smem, s, &mut args!(m, b, a, al, db, st, out, bs, nk, nv, hk, hv));
        }
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn gdn_rmsnorm_gated(
    x: *const c_void, gate: *const c_void, weight: *const c_void, output: *mut c_void, rows: i32, hidden_dim: i32, eps: f32, dtype: i32,
    stream: i64,
) {
    let s = cu_stream(stream);
    let (mut x, mut gate, mut weight, mut output, mut rows, mut hidden_dim, mut eps) = (x, gate, weight, output, rows, hidden_dim, eps);
    let name = if dtype == 0 {
        "_Z24gdn_rmsnorm_gated_kernelI6__halfEvPKT_S3_S3_PS1_iif"
    } else {
        "_Z24gdn_rmsnorm_gated_kernelI13__nv_bfloat16EvPKT_S3_S3_PS1_iif"
    };
    unsafe { launch(name, (rows as u32, 1, 1), (128, 1, 1), 0, s, &mut args!(x, gate, weight, output, rows, hidden_dim, eps)) };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn fused_gdn_gating(
    b: *const c_void, a: *const c_void, a_log: *const f32, dt_bias: *const f32, beta_out: *mut c_void, g_out: *mut c_void,
    total_elements: i32, num_heads: i32, dtype: i32, stream: i64,
) {
    let s = cu_stream(stream);
    let (mut b, mut a, mut al, mut db, mut bo, mut go, mut te, mut nh) = (b, a, a_log, dt_bias, beta_out, g_out, total_elements, num_heads);
    let name = if dtype == 0 {
        "_Z23fused_gdn_gating_kernelI6__halfEvPKT_S3_PKfS5_PS1_S6_ii"
    } else {
        "_Z23fused_gdn_gating_kernelI13__nv_bfloat16EvPKT_S3_PKfS5_PS1_S6_ii"
    };
    unsafe { launch(name, (cdiv_u(total_elements, 256), 1, 1), (256, 1, 1), 0, s, &mut args!(b, a, al, db, bo, go, te, nh)) };
}

// ================================================================================================
// ssm.cu

#[unsafe(no_mangle)]
pub unsafe extern "C" fn selective_scan_cuda(
    x: *const f32, dt: *const f32, a: *const f32, b: *const f32, c: *const f32, d: *const f32, dt_bias: *const f32, state: *mut f32,
    y: *mut f32, batch_size: i32, n_heads: i32, head_dim: i32, d_state: i32, seq_len: i32, dt_min: f32, dt_max: f32, stream: i64,
) {
    let s = cu_stream(stream);
    let n_warps = n_heads.wrapping_mul(head_dim);
    let c_factor = (d_state + 31) / 32;
    let name = match c_factor {
        1 => "_Z15ssm_scan_kernelILi1EEvPKfS1_S1_S1_S1_S1_S1_PfS2_iiiiff",
        2 => "_Z15ssm_scan_kernelILi2EEvPKfS1_S1_S1_S1_S1_S1_PfS2_iiiiff",
        4 => "_Z15ssm_scan_kernelILi4EEvPKfS1_S1_S1_S1_S1_S1_PfS2_iiiiff",
        _ => "_Z15ssm_scan_kernelILi8EEvPKfS1_S1_S1_S1_S1_S1_PfS2_iiiiff",
    };
    let (mut x, mut dt, mut a, mut b, mut c, mut d, mut db, mut st, mut y) = (x, dt, a, b, c, d, dt_bias, state, y);
    let (mut nh, mut hd, mut ds, mut sl, mut dmin, mut dmax) = (n_heads, head_dim, d_state, seq_len, dt_min, dt_max);
    unsafe {
        launch(name, (n_warps as u32, batch_size as u32, 1), (32, 1, 1), 0, s,
               &mut args!(x, dt, a, b, c, d, db, st, y, nh, hd, ds, sl, dmin, dmax))
    };
}

// ================================================================================================
// moe_gemv.cu / moe_gemm.cu / moe_gemm_wmma.cu (+ moe_utils.h)

unsafe extern "C" {
    fn write(fd: i32, buf: *const c_void, n: usize) -> isize;
}

/// `fprintf(stderr, msg)` (unbuffered, like C's stderr).
fn c_stderr(msg: &str) {
    unsafe {
        write(2, msg.as_ptr() as *const c_void, msg.len());
    }
}

/// `ASSERT_THROW`: `throw std::runtime_error(msg)` out of an extern "C" launcher terminates the
/// process (libstdc++'s verbose terminate handler, then abort).
fn throw_runtime_error(msg: &str) -> ! {
    c_stderr(&format!("terminate called after throwing an instance of 'std::runtime_error'\n  what():  {msg}\n"));
    std::process::abort()
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn moe_gemv(
    input: *const c_void, weights: *const c_void, sorted_token_ids: *const i32, expert_ids: *const i32, topk_weights: *const f32,
    output: *mut c_void, num_experts: i32, topk: i32, size_m: i32, size_n: i32, size_k: i32, dtype: i32, stream: i64,
) {
    let s = cu_stream(stream);
    let name = match dtype {
        0 => "_Z15moe_gemv_kernelI6__halfLi256EEvPKT_S3_PKiS5_PKfPS1_iiiii",
        1 => "_Z15moe_gemv_kernelI13__nv_bfloat16Li256EEvPKT_S3_PKiS5_PKfPS1_iiiii",
        _ => return c_stderr("moe_gemv: unsupported dtype.\n"),
    };
    let (mut i, mut w, mut st, mut e, mut tw, mut o) = (input, weights, sorted_token_ids, expert_ids, topk_weights, output);
    let (mut ne, mut tk, mut m, mut n, mut k) = (num_experts, topk, size_m, size_n, size_k);
    unsafe { launch(name, (size_n as u32, size_m as u32, 1), (256, 1, 1), 0, s, &mut args!(i, w, st, e, tw, o, ne, tk, m, n, k)) };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn moe_gemm(
    input: *const c_void, weights: *const c_void, sorted_token_ids: *const i32, expert_ids: *const i32, topk_weights: *const f32,
    output: *mut c_void, num_experts: i32, topk: i32, size_m: i32, size_n: i32, size_k: i32, dtype: i32, stream: i64,
) {
    let s = cu_stream(stream);
    let load_vec_size = if dtype == 2 { 1 } else { 8 };
    if size_k % 64 != 0 {
        throw_runtime_error("size_k must be divisible by BLOCK_K_TILE");
    }
    if size_k % load_vec_size != 0 {
        throw_runtime_error("size_k must be divisible by vector size (2 for fp16/bf16)");
    }
    let name = match dtype {
        0 => "_Z26moe_gemm_vectorized_kernelI6__half7__half2Li64ELi64ELi8EEvPKT_S4_PKiS6_PKfPS2_iiiii",
        1 => "_Z26moe_gemm_vectorized_kernelI13__nv_bfloat1614__nv_bfloat162Li64ELi64ELi8EEvPKT_S4_PKiS6_PKfPS2_iiiii",
        _ => return c_stderr("moe_gemm: unsupported dtype.\n"),
    };
    let (mut i, mut w, mut st, mut e, mut tw, mut o) = (input, weights, sorted_token_ids, expert_ids, topk_weights, output);
    let (mut ne, mut tk, mut m, mut n, mut k) = (num_experts, topk, size_m, size_n, size_k);
    unsafe { launch(name, (cdiv_u(size_n, 64), size_m as u32, 1), (64, 8, 1), 0, s, &mut args!(i, w, st, e, tw, o, ne, tk, m, n, k)) };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn moe_gemm_wmma(
    input: *const c_void, weights: *const c_void, sorted_token_ids: *const i32, expert_ids: *const i32, topk_weights: *const f32,
    output: *mut c_void, num_experts: i32, topk: i32, size_m: i32, size_n: i32, size_k: i32, data_type: i32, stream: i64,
) {
    unsafe {
        let s = cu_stream(stream);
        stream_context(s);
        // calculate_expert_offsets: cudaMallocAsync offsets / counts, memset(counts), count kernel,
        // inclusive scan into offsets + 1, memset(offsets[0]), cudaFreeAsync(counts).
        let mut offsets: sys::CUdeviceptr = 0;
        let _ = sys::cuMemAllocAsync(&mut offsets, (num_experts as i64 + 1).wrapping_mul(4) as usize, s);
        let mut counts: sys::CUdeviceptr = 0;
        let _ = sys::cuMemAllocAsync(&mut counts, (num_experts as i64).wrapping_mul(4) as usize, s);
        if num_experts > 0 {
            let _ = sys::cuMemsetD32Async(counts, 0, num_experts as usize, s);
        }
        let (mut ids, mut cp, mut m) = (expert_ids, counts as *mut i32, size_m);
        launch("_Z30count_tokens_per_expert_kernelPKiPii", (cdiv_u(size_m, 256), 1, 1), (256, 1, 1), 0, s, &mut args!(ids, cp, m));
        let (mut cp2, mut op, mut ne) = (counts as *const i32, offsets as *mut i32, num_experts);
        if num_experts > 0 {
            launch("moe_expert_offsets_scan", (1, 1, 1), (1024, 1, 1), 0, s, &mut args!(cp2, op, ne));
        } else {
            let _ = sys::cuMemsetD32Async(offsets, 0, 1, s);
        }
        if counts != 0 {
            let _ = sys::cuMemFreeAsync(counts, s);
        }
        let name = match data_type {
            0 => Some("_Z23moe_gemm_grouped_kernelI6__halfEvPKT_S3_PKiS5_PKfPS1_iiiii"),
            1 => Some("_Z23moe_gemm_grouped_kernelI13__nv_bfloat16EvPKT_S3_PKiS5_PKfPS1_iiiii"),
            _ => None,
        };
        if let Some(name) = name {
            let (mut i, mut w, mut st, mut of, mut tw, mut o) = (input, weights, sorted_token_ids, offsets as *const i32, topk_weights, output);
            let (mut ne, mut tk, mut m, mut n, mut k) = (num_experts, topk, size_m, size_n, size_k);
            // A_sh 1024 + B_sh 1024 (+ pad 0) + C_sh 4096
            launch(name, (num_experts as u32, cdiv_u(size_n, 32), 1), (128, 1, 1), 1024 + 1024 + 4096, s, &mut args!(i, w, st, of, tw, o, ne, tk, m, n, k));
        }
        if offsets != 0 {
            let _ = sys::cuMemFreeAsync(offsets, s);
        }
    }
}

// ================================================================================================
// attention_prep.cu

/// Block size: the smallest power of two >= head_dim, from 32 up to 1024.
fn ap_block(head_dim: i32) -> u32 {
    let mut b = 32;
    while b < head_dim && b < 1024 {
        b <<= 1;
    }
    b as u32
}

fn ap_name(kind: usize, dtype: i32, neox: bool) -> Option<&'static str> {
    const N: [[[&str; 2]; 3]; 3] = [
        [
            ["_Z23qk_rms_norm_rope_kernelI6__halfLb0EEvPKT_S3_S3_S3_S3_S3_PS1_S4_lllllllliiiiiiiff", "_Z23qk_rms_norm_rope_kernelI6__halfLb1EEvPKT_S3_S3_S3_S3_S3_PS1_S4_lllllllliiiiiiiff"],
            ["_Z23qk_rms_norm_rope_kernelI13__nv_bfloat16Lb0EEvPKT_S3_S3_S3_S3_S3_PS1_S4_lllllllliiiiiiiff", "_Z23qk_rms_norm_rope_kernelI13__nv_bfloat16Lb1EEvPKT_S3_S3_S3_S3_S3_PS1_S4_lllllllliiiiiiiff"],
            ["_Z23qk_rms_norm_rope_kernelIfLb0EEvPKT_S2_S2_S2_S2_S2_PS0_S3_lllllllliiiiiiiff", "_Z23qk_rms_norm_rope_kernelIfLb1EEvPKT_S2_S2_S2_S2_S2_PS0_S3_lllllllliiiiiiiff"],
        ],
        [
            ["_Z33qk_rms_norm_rope_positions_kernelI6__halfLb0EEvPKT_S3_S3_S3_S3_S3_PKjPS1_S6_lllllllliiiiiiff", "_Z33qk_rms_norm_rope_positions_kernelI6__halfLb1EEvPKT_S3_S3_S3_S3_S3_PKjPS1_S6_lllllllliiiiiiff"],
            ["_Z33qk_rms_norm_rope_positions_kernelI13__nv_bfloat16Lb0EEvPKT_S3_S3_S3_S3_S3_PKjPS1_S6_lllllllliiiiiiff", "_Z33qk_rms_norm_rope_positions_kernelI13__nv_bfloat16Lb1EEvPKT_S3_S3_S3_S3_S3_PKjPS1_S6_lllllllliiiiiiff"],
            ["_Z33qk_rms_norm_rope_positions_kernelIfLb0EEvPKT_S2_S2_S2_S2_S2_PKjPS0_S5_lllllllliiiiiiff", "_Z33qk_rms_norm_rope_positions_kernelIfLb1EEvPKT_S2_S2_S2_S2_S2_PKjPS0_S5_lllllllliiiiiiff"],
        ],
        [
            ["_Z34qkv_rms_norm_rope_positions_kernelI6__halfLb0EEvPKT_S3_S3_S3_S3_S3_S3_S3_PKjPS1_S6_S6_lllllllllllliiiiiifff", "_Z34qkv_rms_norm_rope_positions_kernelI6__halfLb1EEvPKT_S3_S3_S3_S3_S3_S3_S3_PKjPS1_S6_S6_lllllllllllliiiiiifff"],
            ["_Z34qkv_rms_norm_rope_positions_kernelI13__nv_bfloat16Lb0EEvPKT_S3_S3_S3_S3_S3_S3_S3_PKjPS1_S6_S6_lllllllllllliiiiiifff", "_Z34qkv_rms_norm_rope_positions_kernelI13__nv_bfloat16Lb1EEvPKT_S3_S3_S3_S3_S3_S3_S3_PKjPS1_S6_S6_lllllllllllliiiiiifff"],
            ["_Z34qkv_rms_norm_rope_positions_kernelIfLb0EEvPKT_S2_S2_S2_S2_S2_S2_S2_PKjPS0_S5_S5_lllllllllllliiiiiifff", "_Z34qkv_rms_norm_rope_positions_kernelIfLb1EEvPKT_S2_S2_S2_S2_S2_S2_S2_PKjPS0_S5_S5_lllllllllllliiiiiifff"],
        ],
    ];
    if !(0..=2).contains(&dtype) {
        return None;
    }
    Some(N[kind][dtype as usize][neox as usize])
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn qk_rms_norm_rope(
    q: *const c_void, k: *const c_void, q_weight: *const c_void, k_weight: *const c_void, cos: *const c_void, sin: *const c_void,
    q_out: *mut c_void, k_out: *mut c_void, q_stride_b: i64, q_stride_h: i64, q_stride_s: i64, q_stride_d: i64, k_stride_b: i64,
    k_stride_h: i64, k_stride_s: i64, k_stride_d: i64, batch: i32, q_heads: i32, k_heads: i32, seq_len: i32, head_dim: i32,
    rot_dim: i32, cos_batch_stride: i32, q_eps: f32, k_eps: f32, is_neox: i32, dtype: i32, stream: i64,
) {
    let Some(name) = ap_name(0, dtype, is_neox != 0) else { return };
    if batch <= 0 || q_heads <= 0 || seq_len <= 0 || head_dim <= 0 || rot_dim <= 0 {
        return;
    }
    let total = batch.wrapping_mul(q_heads.wrapping_add(k_heads)).wrapping_mul(seq_len);
    if total <= 0 {
        return;
    }
    let s = cu_stream(stream);
    let (mut q, mut k, mut qw, mut kw, mut c, mut sn, mut qo, mut ko) = (q, k, q_weight, k_weight, cos, sin, q_out, k_out);
    let (mut a0, mut a1, mut a2, mut a3, mut b0, mut b1, mut b2, mut b3) = (q_stride_b, q_stride_h, q_stride_s, q_stride_d, k_stride_b, k_stride_h, k_stride_s, k_stride_d);
    let (mut ba, mut qh, mut kh, mut sl, mut hd, mut rd, mut cbs, mut qe, mut ke) = (batch, q_heads, k_heads, seq_len, head_dim, rot_dim, cos_batch_stride, q_eps, k_eps);
    unsafe {
        launch(name, (total as u32, 1, 1), (ap_block(head_dim), 1, 1), 0, s,
               &mut args!(q, k, qw, kw, c, sn, qo, ko, a0, a1, a2, a3, b0, b1, b2, b3, ba, qh, kh, sl, hd, rd, cbs, qe, ke))
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn qk_rms_norm_rope_positions(
    q: *const c_void, k: *const c_void, q_weight: *const c_void, k_weight: *const c_void, cos: *const c_void, sin: *const c_void,
    positions: *const c_void, q_out: *mut c_void, k_out: *mut c_void, q_stride_b: i64, q_stride_h: i64, q_stride_s: i64,
    q_stride_d: i64, k_stride_b: i64, k_stride_h: i64, k_stride_s: i64, k_stride_d: i64, batch: i32, q_heads: i32, k_heads: i32,
    seq_len: i32, head_dim: i32, rot_dim: i32, q_eps: f32, k_eps: f32, is_neox: i32, dtype: i32, stream: i64,
) {
    let Some(name) = ap_name(1, dtype, is_neox != 0) else { return };
    if batch <= 0 || q_heads <= 0 || seq_len <= 0 || head_dim <= 0 || rot_dim <= 0 {
        return;
    }
    let total = batch.wrapping_mul(q_heads.wrapping_add(k_heads)).wrapping_mul(seq_len);
    if total <= 0 {
        return;
    }
    let s = cu_stream(stream);
    let (mut q, mut k, mut qw, mut kw, mut c, mut sn, mut pos, mut qo, mut ko) = (q, k, q_weight, k_weight, cos, sin, positions, q_out, k_out);
    let (mut a0, mut a1, mut a2, mut a3, mut b0, mut b1, mut b2, mut b3) = (q_stride_b, q_stride_h, q_stride_s, q_stride_d, k_stride_b, k_stride_h, k_stride_s, k_stride_d);
    let (mut ba, mut qh, mut kh, mut sl, mut hd, mut rd, mut qe, mut ke) = (batch, q_heads, k_heads, seq_len, head_dim, rot_dim, q_eps, k_eps);
    unsafe {
        launch(name, (total as u32, 1, 1), (ap_block(head_dim), 1, 1), 0, s,
               &mut args!(q, k, qw, kw, c, sn, pos, qo, ko, a0, a1, a2, a3, b0, b1, b2, b3, ba, qh, kh, sl, hd, rd, qe, ke))
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn qkv_rms_norm_rope_positions(
    q: *const c_void, k: *const c_void, v: *const c_void, q_weight: *const c_void, k_weight: *const c_void, v_weight: *const c_void,
    cos: *const c_void, sin: *const c_void, positions: *const c_void, q_out: *mut c_void, k_out: *mut c_void, v_out: *mut c_void,
    q_stride_b: i64, q_stride_h: i64, q_stride_s: i64, q_stride_d: i64, k_stride_b: i64, k_stride_h: i64, k_stride_s: i64,
    k_stride_d: i64, v_stride_b: i64, v_stride_h: i64, v_stride_s: i64, v_stride_d: i64, batch: i32, q_heads: i32, k_heads: i32,
    seq_len: i32, head_dim: i32, rot_dim: i32, q_eps: f32, k_eps: f32, v_eps: f32, is_neox: i32, dtype: i32, stream: i64,
) {
    let Some(name) = ap_name(2, dtype, is_neox != 0) else { return };
    if batch <= 0 || q_heads <= 0 || k_heads <= 0 || seq_len <= 0 || head_dim <= 0 || rot_dim <= 0 {
        return;
    }
    let total = batch.wrapping_mul(q_heads.wrapping_add(k_heads).wrapping_add(k_heads)).wrapping_mul(seq_len);
    if total <= 0 {
        return;
    }
    let s = cu_stream(stream);
    let (mut q, mut k, mut v, mut qw, mut kw, mut vw, mut c, mut sn, mut pos) = (q, k, v, q_weight, k_weight, v_weight, cos, sin, positions);
    let (mut qo, mut ko, mut vo) = (q_out, k_out, v_out);
    let (mut a0, mut a1, mut a2, mut a3, mut b0, mut b1, mut b2, mut b3) = (q_stride_b, q_stride_h, q_stride_s, q_stride_d, k_stride_b, k_stride_h, k_stride_s, k_stride_d);
    let (mut c0, mut c1, mut c2, mut c3) = (v_stride_b, v_stride_h, v_stride_s, v_stride_d);
    let (mut ba, mut qh, mut kh, mut sl, mut hd, mut rd, mut qe, mut ke, mut ve) = (batch, q_heads, k_heads, seq_len, head_dim, rot_dim, q_eps, k_eps, v_eps);
    unsafe {
        launch(name, (total as u32, 1, 1), (ap_block(head_dim), 1, 1), 0, s,
               &mut args!(q, k, v, qw, kw, vw, c, sn, pos, qo, ko, vo, a0, a1, a2, a3, b0, b1, b2, b3, c0, c1, c2, c3, ba, qh, kh, sl, hd, rd, qe, ke, ve))
    };
}

// ================================================================================================
// sort.cu

/// Interned kernel names built at run time (template instances).
fn intern(s: String) -> &'static str {
    static NAMES: OnceLock<Mutex<HashMap<String, &'static str>>> = OnceLock::new();
    let mut m = NAMES.get_or_init(|| Mutex::new(HashMap::new())).lock().unwrap();
    if let Some(v) = m.get(&s) {
        return v;
    }
    let v: &'static str = Box::leak(s.clone().into_boxed_str());
    m.insert(s, v);
    v
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn apply_sparse_penalties_f32(
    x: *const c_void, dst: *mut c_void, token_ids: *const u32, counts: *const f32, n: i32, n_tokens: i32, frequency_penalty: f32,
    presence_penalty: f32, repetition_penalty: f32, stream: i64,
) {
    if n <= 0 {
        return;
    }
    let s = cu_stream(stream);
    let (mut xp, mut dp, mut nn) = (x as *const f32, dst as *mut f32, n);
    unsafe { launch("_Z15copy_f32_kernelPKfPfi", (cdiv_u(n, 256), 1, 1), (256, 1, 1), 0, s, &mut args!(xp, dp, nn)) };
    if n_tokens <= 0 {
        return;
    }
    let (mut t, mut c, mut nt, mut f, mut p, mut r) = (token_ids, counts, n_tokens, frequency_penalty, presence_penalty, repetition_penalty);
    unsafe {
        launch("_Z33apply_sparse_penalties_f32_kernelPfPKjPKfiifff", (cdiv_u(n_tokens, 256), 1, 1), (256, 1, 1), 0, s,
               &mut args!(dp, t, c, nn, nt, f, p, r))
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn apply_sparse_logits_bias_f32(
    x: *const c_void, dst: *mut c_void, token_ids: *const u32, biases: *const f32, n: i32, n_tokens: i32, stream: i64,
) {
    if n <= 0 {
        return;
    }
    let s = cu_stream(stream);
    let (mut xp, mut dp, mut nn) = (x as *const f32, dst as *mut f32, n);
    unsafe { launch("_Z15copy_f32_kernelPKfPfi", (cdiv_u(n, 256), 1, 1), (256, 1, 1), 0, s, &mut args!(xp, dp, nn)) };
    if n_tokens <= 0 {
        return;
    }
    let (mut t, mut b, mut nt) = (token_ids, biases, n_tokens);
    unsafe {
        launch("_Z35apply_sparse_logits_bias_f32_kernelPfPKjPKfii", (cdiv_u(n_tokens, 256), 1, 1), (256, 1, 1), 0, s, &mut args!(dp, t, b, nn, nt))
    };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn apply_causal_mask_f32(
    scores: *mut c_void, batch_heads: i32, q_len: i32, kv_len: i32, q_offset: i32, prefix_len: i32, stream: i64,
) {
    if batch_heads <= 0 || q_len <= 0 || kv_len <= 0 {
        return;
    }
    let s = cu_stream(stream);
    let total = batch_heads.wrapping_mul(q_len).wrapping_mul(kv_len);
    let (mut sc, mut bh, mut ql, mut kl, mut qo, mut pl) = (scores as *mut f32, batch_heads, q_len, kv_len, q_offset, prefix_len);
    unsafe { launch("_Z28apply_causal_mask_f32_kernelPfiiiii", (cdiv_u(total, 256), 1, 1), (256, 1, 1), 0, s, &mut args!(sc, bh, ql, kl, qo, pl)) };
}

/// Mangled template-argument spelling of a dtype: 0 f32, 1 f16, 2 bf16.
fn tspell(t: usize) -> &'static str {
    ["f", "6__half", "13__nv_bfloat16"][t]
}

fn vec8_aligned(p: *const c_void) -> bool {
    (p as usize) % 16 == 0
}

unsafe fn rms_residual(t: usize, x: *const c_void, residual: *const c_void, weight: *const c_void, scale: *const c_void, dst: *mut c_void, nrows: i32, ncols: i32, eps: f32, stream: i64) {
    if nrows <= 0 || ncols <= 0 {
        return;
    }
    let s = cu_stream(stream);
    let (mut x, mut r, mut w, mut sc, mut d, mut nc, mut e) = (x, residual, weight, scale, dst, ncols, eps);
    let tail = if t == 0 { "EvPKT_S2_S2_S2_PS0_if" } else { "EvPKT_S3_S3_S3_PS1_if" };
    unsafe {
        if t != 0 && ncols % 8 == 0 && vec8_aligned(x) && vec8_aligned(r) && vec8_aligned(w) && vec8_aligned(d) {
            let vc = ncols / 8;
            let block = ((vc + 31) / 32 * 32).clamp(32, 1024);
            let name = intern(format!("_Z29rms_norm_residual_vec8_kernelI{}{}", tspell(t), tail));
            launch(name, (nrows as u32, 1, 1), (block as u32, 1, 1), 0, s, &mut args!(x, r, w, sc, d, nc, e));
            return;
        }
        let block = if ncols < 1024 { 32 } else { 1024 };
        let name = intern(format!("_Z24rms_norm_residual_kernelI{}{}", tspell(t), tail));
        launch(name, (nrows as u32, 1, 1), (block, 1, 1), 0, s, &mut args!(x, r, w, sc, d, nc, e));
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn rms_norm_residual_f32(x: *const c_void, residual: *const c_void, weight: *const c_void, scale: *const c_void, dst: *mut c_void, nrows: i32, ncols: i32, eps: f32, stream: i64) {
    unsafe { rms_residual(0, x, residual, weight, scale, dst, nrows, ncols, eps, stream) }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rms_norm_residual_f16(x: *const c_void, residual: *const c_void, weight: *const c_void, scale: *const c_void, dst: *mut c_void, nrows: i32, ncols: i32, eps: f32, stream: i64) {
    unsafe { rms_residual(1, x, residual, weight, scale, dst, nrows, ncols, eps, stream) }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rms_norm_residual_bf16(x: *const c_void, residual: *const c_void, weight: *const c_void, scale: *const c_void, dst: *mut c_void, nrows: i32, ncols: i32, eps: f32, stream: i64) {
    unsafe { rms_residual(2, x, residual, weight, scale, dst, nrows, ncols, eps, stream) }
}

unsafe fn rms_residual_then(
    t: usize, x: *const c_void, residual: *const c_void, rw: *const c_void, scale: *const c_void, nw: *const c_void, rdst: *mut c_void,
    ndst: *mut c_void, nrows: i32, ncols: i32, reps: f32, neps: f32, stream: i64,
) {
    if nrows <= 0 || ncols <= 0 {
        return;
    }
    let s = cu_stream(stream);
    let (mut x, mut r, mut rw_, mut sc, mut nw_, mut rd, mut nd, mut nc, mut re, mut ne) = (x, residual, rw, scale, nw, rdst, ndst, ncols, reps, neps);
    let tail = if t == 0 { "EvPKT_S2_S2_S2_S2_PS0_S3_iff" } else { "EvPKT_S3_S3_S3_S3_PS1_S4_iff" };
    unsafe {
        if t != 0 && ncols % 8 == 0 && vec8_aligned(x) && vec8_aligned(r) && vec8_aligned(rw) && vec8_aligned(rdst) && vec8_aligned(nw) && vec8_aligned(ndst) {
            let vc = ncols / 8;
            let block = ((vc + 31) / 32 * 32).clamp(32, 1024);
            let name = intern(format!("_Z43rms_norm_residual_then_rms_norm_vec8_kernelI{}{}", tspell(t), tail));
            launch(name, (nrows as u32, 1, 1), (block as u32, 1, 1), 0, s, &mut args!(x, r, rw_, sc, nw_, rd, nd, nc, re, ne));
            return;
        }
        let block = if ncols < 1024 { 32 } else { 1024 };
        let name = intern(format!("_Z38rms_norm_residual_then_rms_norm_kernelI{}{}", tspell(t), tail));
        launch(name, (nrows as u32, 1, 1), (block, 1, 1), 0, s, &mut args!(x, r, rw_, sc, nw_, rd, nd, nc, re, ne));
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn rms_norm_residual_then_rms_norm_f32(x: *const c_void, residual: *const c_void, residual_weight: *const c_void, scale: *const c_void, norm_weight: *const c_void, residual_dst: *mut c_void, norm_dst: *mut c_void, nrows: i32, ncols: i32, residual_eps: f32, norm_eps: f32, stream: i64) {
    unsafe { rms_residual_then(0, x, residual, residual_weight, scale, norm_weight, residual_dst, norm_dst, nrows, ncols, residual_eps, norm_eps, stream) }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rms_norm_residual_then_rms_norm_f16(x: *const c_void, residual: *const c_void, residual_weight: *const c_void, scale: *const c_void, norm_weight: *const c_void, residual_dst: *mut c_void, norm_dst: *mut c_void, nrows: i32, ncols: i32, residual_eps: f32, norm_eps: f32, stream: i64) {
    unsafe { rms_residual_then(1, x, residual, residual_weight, scale, norm_weight, residual_dst, norm_dst, nrows, ncols, residual_eps, norm_eps, stream) }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rms_norm_residual_then_rms_norm_bf16(x: *const c_void, residual: *const c_void, residual_weight: *const c_void, scale: *const c_void, norm_weight: *const c_void, residual_dst: *mut c_void, norm_dst: *mut c_void, nrows: i32, ncols: i32, residual_eps: f32, norm_eps: f32, stream: i64) {
    unsafe { rms_residual_then(2, x, residual, residual_weight, scale, norm_weight, residual_dst, norm_dst, nrows, ncols, residual_eps, norm_eps, stream) }
}

unsafe fn rms_strided(t: usize, x: *const c_void, weight: *const c_void, dst: *mut c_void, sb: i64, sh: i64, ss: i64, sd: i64, batch: i32, heads: i32, seq_len: i32, head_dim: i32, eps: f32, stream: i64) {
    if batch <= 0 || heads <= 0 || seq_len <= 0 || head_dim <= 0 {
        return;
    }
    let s = cu_stream(stream);
    let total = batch.wrapping_mul(heads).wrapping_mul(seq_len);
    let tail = if t == 0 { "EvPKT_S2_PS0_lllliiiif" } else { "EvPKT_S3_PS1_lllliiiif" };
    let name = intern(format!("_Z26rms_norm_strided_4d_kernelI{}{}", tspell(t), tail));
    let (mut x, mut w, mut d, mut a, mut b, mut c, mut dd, mut ba, mut he, mut sl, mut hd, mut e) = (x, weight, dst, sb, sh, ss, sd, batch, heads, seq_len, head_dim, eps);
    unsafe { launch(name, (total as u32, 1, 1), (ap_block(head_dim), 1, 1), 0, s, &mut args!(x, w, d, a, b, c, dd, ba, he, sl, hd, e)) };
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn rms_norm_strided_4d_f32(x: *const c_void, weight: *const c_void, dst: *mut c_void, stride_b: i64, stride_h: i64, stride_s: i64, stride_d: i64, batch: i32, heads: i32, seq_len: i32, head_dim: i32, eps: f32, stream: i64) {
    unsafe { rms_strided(0, x, weight, dst, stride_b, stride_h, stride_s, stride_d, batch, heads, seq_len, head_dim, eps, stream) }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rms_norm_strided_4d_f16(x: *const c_void, weight: *const c_void, dst: *mut c_void, stride_b: i64, stride_h: i64, stride_s: i64, stride_d: i64, batch: i32, heads: i32, seq_len: i32, head_dim: i32, eps: f32, stream: i64) {
    unsafe { rms_strided(1, x, weight, dst, stride_b, stride_h, stride_s, stride_d, batch, heads, seq_len, head_dim, eps, stream) }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn rms_norm_strided_4d_bf16(x: *const c_void, weight: *const c_void, dst: *mut c_void, stride_b: i64, stride_h: i64, stride_s: i64, stride_d: i64, batch: i32, heads: i32, seq_len: i32, head_dim: i32, eps: f32, stream: i64) {
    unsafe { rms_strided(2, x, weight, dst, stride_b, stride_h, stride_s, stride_d, batch, heads, seq_len, head_dim, eps, stream) }
}

unsafe extern "C" {
    fn malloc(n: usize) -> *mut c_void;
    fn free(p: *mut c_void);
}

/// `next_power_of_2(int)` of sort.cu.
fn next_power_of_2(x: i32) -> i32 {
    let mut n: i32 = 1;
    while n < x {
        n = n.wrapping_mul(2);
    }
    n
}

/// ASORT_OP: per-row bitonic argsort through padded scratch rows. `pad` is the value written
/// into the padding (`numeric_limits<T>::max()` ascending / `::min()` descending); `None` for
/// f16/bf16, where `numeric_limits<__half>` is not specialised and nvcc drops the stores: the
/// padding is whatever the uninitialised `malloc` block holds (reproduced as-is).
unsafe fn asort<T: Copy>(tspell: &str, asc: bool, pad: Option<T>, x1: *mut c_void, dst1: *mut c_void, nrows: i32, ncols: i32, inplace: bool, stream: i64) {
    unsafe {
        let s = cu_stream(stream);
        stream_context(s);
        let es = std::mem::size_of::<T>();
        let ncols_pad = next_power_of_2(ncols);
        let mut x_pad: sys::CUdeviceptr = 0;
        let mut d_pad: sys::CUdeviceptr = 0;
        let _ = sys::cuMemAllocAsync(&mut x_pad, (ncols_pad as i64 as usize).wrapping_mul(es), s);
        let _ = sys::cuMemAllocAsync(&mut d_pad, (ncols_pad as i64 as usize).wrapping_mul(4), s);
        let indices = malloc((ncols_pad as i64 as usize).wrapping_mul(4)) as *mut u32;
        for i in 0..ncols_pad.max(0) {
            *indices.add(i as usize) = i as u32;
        }
        let npad = ncols_pad - ncols;
        let values = malloc((npad as i64 as usize).wrapping_mul(es)) as *mut T;
        if let Some(p) = pad {
            for i in 0..npad.max(0) {
                *values.add(i as usize) = p;
            }
        }
        let tpb = if 1024 > ncols_pad { ncols_pad } else { 1024 };
        let bpr = (ncols_pad + tpb - 1) / tpb;
        let name = intern(format!("_Z19bitonic_sort_kernelI{tspell}Lb{}EEvPT_Pjii", asc as u8));
        let x = x1 as *mut T;
        let dst = dst1 as *mut u32;
        for row in 0..nrows {
            let x_row = x.wrapping_offset(row.wrapping_mul(ncols) as isize);
            let d_row = dst.wrapping_offset(row.wrapping_mul(ncols) as isize);
            let nbytes = (ncols as i64 as usize).wrapping_mul(es);
            let _ = sys::cuMemcpyDtoDAsync_v2(x_pad, x_row as sys::CUdeviceptr, nbytes, s);
            if npad > 0 {
                let _ = sys::cuMemcpyHtoDAsync_v2(x_pad + nbytes as u64, values as *const c_void, npad as usize * es, s);
            }
            let _ = sys::cuMemcpyHtoDAsync_v2(d_pad, indices as *const c_void, ncols_pad as usize * 4, s);
            let mut k = 2;
            while k <= ncols_pad {
                let mut j = k >> 1;
                while j > 0 {
                    let (mut a, mut b, mut jj, mut kk) = (x_pad as *mut T, d_pad as *mut u32, j, k);
                    launch(name, (bpr as u32, 1, 1), (tpb as u32, 1, 1), 0, s, &mut args!(a, b, jj, kk));
                    j >>= 1;
                }
                k <<= 1;
            }
            if inplace {
                let _ = sys::cuMemcpyDtoDAsync_v2(x_row as sys::CUdeviceptr, x_pad, nbytes, s);
            }
            let _ = sys::cuMemcpyDtoDAsync_v2(d_row as sys::CUdeviceptr, d_pad, (ncols as i64 as usize).wrapping_mul(4), s);
        }
        let _ = sys::cuMemFreeAsync(x_pad, s);
        let _ = sys::cuMemFreeAsync(d_pad, s);
        free(indices as *mut c_void);
        free(values as *mut c_void);
    }
}

macro_rules! asort_ops {
    ($($name:ident $t:ty, $sp:literal, $asc:literal, $pad:expr;)*) => {$(
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $name(x: *mut c_void, dst: *mut c_void, nrows: i32, ncols: i32, inplace: bool, stream: i64) {
            unsafe { asort::<$t>($sp, $asc, $pad, x, dst, nrows, ncols, inplace, stream) }
        }
    )*};
}
asort_ops! {
    asort_asc_bf16 u16, "13__nv_bfloat16", true, None;
    asort_desc_bf16 u16, "13__nv_bfloat16", false, None;
    asort_asc_f16 u16, "6__half", true, None;
    asort_desc_f16 u16, "6__half", false, None;
    asort_asc_f32 f32, "f", true, Some(f32::MAX);
    asort_desc_f32 f32, "f", false, Some(f32::MIN_POSITIVE);
    asort_asc_f64 f64, "d", true, Some(f64::MAX);
    asort_desc_f64 f64, "d", false, Some(f64::MIN_POSITIVE);
    asort_asc_u8 u8, "h", true, Some(u8::MAX);
    asort_desc_u8 u8, "h", false, Some(u8::MIN);
    asort_asc_u32 u32, "j", true, Some(u32::MAX);
    asort_desc_u32 u32, "j", false, Some(u32::MIN);
    asort_asc_i64 i64, "l", true, Some(i64::MAX);
    asort_desc_i64 i64, "l", false, Some(i64::MIN);
}

unsafe fn topk_small(t: usize, es: usize, input: *const c_void, values_out: *mut c_void, indices_out: *mut u32, nrows: i32, ncols: i32, k: i32, stream: i64) {
    let s = cu_stream(stream);
    let block = if ncols <= 64 { 64 } else if ncols <= 128 { 128 } else if ncols <= 256 { 256 } else { 512 };
    let smem = (ncols as i64 as usize).wrapping_mul(es).wrapping_add(ncols as i64 as usize);
    let tail = if t == 0 { "EvPKT_PS0_Pjiii" } else { "EvPKT_PS1_Pjiii" };
    let name = intern(format!("_Z11topk_kernelI{}{}", tspell(t), tail));
    let (mut i, mut v, mut ix, mut nr, mut nc, mut kk) = (input, values_out, indices_out, nrows, ncols, k);
    unsafe { launch(name, (nrows as u32, 1, 1), (block, 1, 1), smem as u32, s, &mut args!(i, v, ix, nr, nc, kk)) };
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn topk_f32(input: *const c_void, values_out: *mut c_void, indices_out: *mut c_void, nrows: i32, ncols: i32, k: i32, stream: i64) {
    unsafe { topk_small(0, 4, input, values_out, indices_out as *mut u32, nrows, ncols, k, stream) }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn topk_bf16(input: *const c_void, values_out: *mut c_void, indices_out: *mut c_void, nrows: i32, ncols: i32, k: i32, stream: i64) {
    unsafe { topk_small(2, 2, input, values_out, indices_out as *mut u32, nrows, ncols, k, stream) }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn topk_f16(input: *const c_void, values_out: *mut c_void, indices_out: *mut c_void, nrows: i32, ncols: i32, k: i32, stream: i64) {
    unsafe { topk_small(1, 2, input, values_out, indices_out as *mut u32, nrows, ncols, k, stream) }
}

unsafe fn router(
    t: usize, logits: *const c_void, weights: *mut c_void, ids: *mut c_void, selection_bias: *const c_void, expert_scale: *const c_void,
    n_rows: i32, n_experts: i32, top_k: i32, score_mode: i32, weight_mode: i32, renormalize: bool, clamp_logits: bool, clamp_min: f32,
    clamp_max: f32, norm_min: f32, output_scale: f32, stream: i64,
) {
    if ![1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 576].contains(&n_experts) {
        return;
    }
    let s = cu_stream(stream);
    let hb = !selection_bias.is_null();
    let hs = !expert_scale.is_null();
    let tail = if t == 0 { "EEvPKT_PfPjPKfS6_iiiibbffff" } else { "EEvPKT_PfPjPKfS7_iiiibbffff" };
    let name = intern(format!("_Z22moe_router_topk_kernelI{}Li{}ELb{}ELb{}{}", tspell(t), n_experts, hb as u8, hs as u8, tail));
    let (mut l, mut w, mut id, mut b, mut es) = (logits, weights, ids, selection_bias, expert_scale);
    let (mut nr, mut tk, mut sm, mut wm, mut rn, mut cl) = (n_rows, top_k, score_mode, weight_mode, renormalize as u8, clamp_logits as u8);
    let (mut cmin, mut cmax, mut nmin, mut os) = (clamp_min, clamp_max, norm_min, output_scale);
    unsafe {
        launch(name, (((n_rows + 3) / 4) as u32, 1, 1), (32, 4, 1), 0, s,
               &mut args!(l, w, id, b, es, nr, tk, sm, wm, rn, cl, cmin, cmax, nmin, os))
    };
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn moe_router_topk_f32(
    logits: *const c_void, weights: *mut c_void, ids: *mut c_void, selection_bias: *const c_void, expert_scale: *const c_void, nrows: i32,
    n_experts: i32, top_k: i32, score_mode: i32, weight_mode: i32, renormalize: bool, clamp_logits: bool, clamp_min: f32, clamp_max: f32,
    norm_min: f32, output_scale: f32, stream: i64,
) {
    unsafe { router(0, logits, weights, ids, selection_bias, expert_scale, nrows, n_experts, top_k, score_mode, weight_mode, renormalize, clamp_logits, clamp_min, clamp_max, norm_min, output_scale, stream) }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn moe_router_topk_f16(
    logits: *const c_void, weights: *mut c_void, ids: *mut c_void, selection_bias: *const c_void, expert_scale: *const c_void, nrows: i32,
    n_experts: i32, top_k: i32, score_mode: i32, weight_mode: i32, renormalize: bool, clamp_logits: bool, clamp_min: f32, clamp_max: f32,
    norm_min: f32, output_scale: f32, stream: i64,
) {
    unsafe { router(1, logits, weights, ids, selection_bias, expert_scale, nrows, n_experts, top_k, score_mode, weight_mode, renormalize, clamp_logits, clamp_min, clamp_max, norm_min, output_scale, stream) }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn moe_router_topk_bf16(
    logits: *const c_void, weights: *mut c_void, ids: *mut c_void, selection_bias: *const c_void, expert_scale: *const c_void, nrows: i32,
    n_experts: i32, top_k: i32, score_mode: i32, weight_mode: i32, renormalize: bool, clamp_logits: bool, clamp_min: f32, clamp_max: f32,
    norm_min: f32, output_scale: f32, stream: i64,
) {
    unsafe { router(2, logits, weights, ids, selection_bias, expert_scale, nrows, n_experts, top_k, score_mode, weight_mode, renormalize, clamp_logits, clamp_min, clamp_max, norm_min, output_scale, stream) }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn topk_large_f32(
    input: *const f32, block_values: *mut f32, block_indices: *mut u32, block_maxes: *mut f32, block_sums: *mut f32, values_out: *mut f32,
    indices_out: *mut u32, softmax_info_out: *mut f32, ncols: i32, k: i32, chunk_size: i32, nblocks: i32, inv_temperature: f32, stream: i64,
) {
    let s = cu_stream(stream);
    let smem1 = chunk_size as i64 as usize;
    let smem2 = (nblocks as i64 as usize).wrapping_mul(k as i64 as usize);
    let (mut i, mut bv, mut bi, mut bm, mut bs) = (input, block_values, block_indices, block_maxes, block_sums);
    let (mut nc, mut kk, mut cs, mut nb, mut it) = (ncols, k, chunk_size, nblocks, inv_temperature);
    let (mut vo, mut io, mut so) = (values_out, indices_out, softmax_info_out);
    unsafe {
        launch("_Z21topk_large_stage1_f32PKfPfPjS1_S1_iiif", (nblocks as u32, 1, 1), (256, 1, 1), smem1 as u32, s, &mut args!(i, bv, bi, bm, bs, nc, kk, cs, it));
        launch("_Z21topk_large_stage2_f32PKfPKjS0_S0_PfPjS3_ii", (1, 1, 1), (256, 1, 1), smem2 as u32, s, &mut args!(bv, bi, bm, bs, vo, io, so, nb, kk));
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn topk_large_f32_packed(
    input: *const f32, block_values: *mut f32, block_indices: *mut u32, block_maxes: *mut f32, block_sums: *mut f32, packed_out: *mut f32,
    ncols: i32, k: i32, chunk_size: i32, nblocks: i32, inv_temperature: f32, stream: i64,
) {
    let s = cu_stream(stream);
    let smem1 = chunk_size as i64 as usize;
    let smem2 = (nblocks as i64 as usize).wrapping_mul(k as i64 as usize);
    let (mut i, mut bv, mut bi, mut bm, mut bs, mut po) = (input, block_values, block_indices, block_maxes, block_sums, packed_out);
    let (mut nc, mut kk, mut cs, mut nb, mut it) = (ncols, k, chunk_size, nblocks, inv_temperature);
    unsafe {
        launch("_Z21topk_large_stage1_f32PKfPfPjS1_S1_iiif", (nblocks as u32, 1, 1), (256, 1, 1), smem1 as u32, s, &mut args!(i, bv, bi, bm, bs, nc, kk, cs, it));
        launch("_Z28topk_large_stage2_f32_packedPKfPKjS0_S0_Pfii", (1, 1, 1), (256, 1, 1), smem2 as u32, s, &mut args!(bv, bi, bm, bs, po, nb, kk));
    }
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn top1_large_f32_packed(
    input: *const f32, block_values: *mut f32, block_indices: *mut u32, packed_out: *mut f32, ncols: i32, chunk_size: i32, nblocks: i32, stream: i64,
) {
    let s = cu_stream(stream);
    let (mut i, mut bv, mut bi, mut po, mut nc, mut cs, mut nb) = (input, block_values, block_indices, packed_out, ncols, chunk_size, nblocks);
    unsafe {
        launch("_Z21top1_large_stage1_f32PKfPfPjii", (nblocks as u32, 1, 1), (256, 1, 1), 0, s, &mut args!(i, bv, bi, nc, cs));
        launch("_Z28top1_large_stage2_f32_packedPKfPKjPfi", (1, 1, 1), (256, 1, 1), 0, s, &mut args!(bv, bi, po, nb));
    }
}
