// GENERATED by gen.py from ../mistralrs-quant-c/src/launch.rs -- edit the port, then regenerate.
//! Pure-Rust twins of the group-C extern "C" host launchers of mistralrs-quant
//! (libmistralrsquant.a: mmvq_gguf.cu, mmq_quantize.cu, mmq_instance_*.cu): same names, same
//! parameter lists and C ABI as the declarations in mistralrs-quant/src/gguf/ffi.rs, same grid /
//! block / shared-memory selection and host-side control flow, launching the oxide kernels on the
//! caller's stream through the CUDA driver API.
//!
//! libmistralrsquant.a is built with `--default-stream per-thread` (`__cudaLaunchKernel_ptsz`):
//! a null `stream` is the per-thread default stream, so it is launched here as
//! `CU_STREAM_PER_THREAD`.
//!
//! The oxide module is loaded once per CUDA context (the stream's context, or the current one for
//! the null stream; if no context is current, device 0's primary context, as the runtime API would)
//! and its functions are cached. The module image is the `#[cuda_module]` bundle embedded in the
//! running executable; if there is none, the PTX file named by `$MISTRALRS_QUANT_C_PTX`, else
//! `<crate>/mistralrs_quant_c.ptx`.
//!
//! Like the C launchers (`<<<>>>` without error checks), launch failures are dropped. The C
//! host-side `GGML_ASSERT`s of the MMQ launchers (fastdiv divisor 0, too many stream-k blocks)
//! print the same message and abort.
//!
//! Every launched kernel is also recorded (by its reference instance key) in `LAUNCHED`, so the
//! gate can check that each reference instance was reached through its Rust twin.
#![allow(clippy::missing_safety_doc, clippy::too_many_arguments)]
use crate::cu as sys;
use std::collections::{HashMap, HashSet};
use std::ffi::{CString, c_void};
use std::sync::{Mutex, OnceLock};

struct Module {
    module: sys::CUmodule,
    functions: HashMap<String, sys::CUfunction>,
}
// CUmodule / CUfunction are driver handles, valid from any thread of the process.
unsafe impl Send for Module {}

static MODULES: OnceLock<Mutex<HashMap<usize, Module>>> = OnceLock::new();

/// Reference instance keys launched so far (see the module docs).
pub static LAUNCHED: Mutex<Option<HashSet<String>>> = Mutex::new(None);

fn record(key: String) {
    LAUNCHED.lock().unwrap().get_or_insert_with(HashSet::new).insert(key);
}

fn module_image() -> &'static [u8] {
    crate::image::quant_c()
}

fn check(r: sys::CUresult, what: &str) {
    assert!(r == 0, "mistralrs-quant-c: {what} failed: {r:?}");
}

/// The context `stream` belongs to (the current context for the null stream).
unsafe fn stream_context(stream: sys::CUstream) -> sys::CUcontext {
    unsafe {
        check(sys::cuInit(0), "cuInit");
        let mut ctx: sys::CUcontext = std::ptr::null_mut();
        if !stream.is_null() {
            check(sys::cuStreamGetCtx(stream, &mut ctx), "cuStreamGetCtx");
            return ctx;
        }
        check(sys::cuCtxGetCurrent(&mut ctx), "cuCtxGetCurrent");
        if ctx.is_null() {
            let mut dev: sys::CUdevice = 0;
            check(sys::cuDeviceGet(&mut dev, 0), "cuDeviceGet");
            check(sys::cuDevicePrimaryCtxRetain(&mut ctx, dev), "cuDevicePrimaryCtxRetain");
            check(sys::cuCtxSetCurrent(ctx), "cuCtxSetCurrent");
        }
        ctx
    }
}

/// The oxide kernel `name` in `stream`'s context (loading the module on first use).
unsafe fn function(name: &str, stream: sys::CUstream) -> sys::CUfunction {
    unsafe {
        let ctx = stream_context(stream);
        let mut map = MODULES.get_or_init(|| Mutex::new(HashMap::new())).lock().unwrap();
        let m = map.entry(ctx as usize).or_insert_with(|| {
            let mut cur: sys::CUcontext = std::ptr::null_mut();
            check(sys::cuCtxGetCurrent(&mut cur), "cuCtxGetCurrent");
            if cur != ctx {
                check(sys::cuCtxPushCurrent_v2(ctx), "cuCtxPushCurrent");
            }
            let image = module_image();
            let mut module: sys::CUmodule = std::ptr::null_mut();
            check(sys::cuModuleLoadData(&mut module, image.as_ptr() as *const c_void), "cuModuleLoadData");
            if cur != ctx {
                let mut popped: sys::CUcontext = std::ptr::null_mut();
                check(sys::cuCtxPopCurrent_v2(&mut popped), "cuCtxPopCurrent");
            }
            Module { module, functions: HashMap::new() }
        });
        let module = m.module;
        if let Some(f) = m.functions.get(name) {
            return *f;
        }
        let mut f: sys::CUfunction = std::ptr::null_mut();
        let c = CString::new(name).unwrap();
        check(sys::cuModuleGetFunction(&mut f, module, c.as_ptr()), name);
        m.functions.insert(name.to_string(), f);
        f
    }
}

/// `CU_STREAM_PER_THREAD`: what a null stream means to a `_ptsz` launch.
const PER_THREAD: usize = 0x2;

/// One kernel argument, passed by value (its bytes).
#[derive(Clone, Copy)]
pub enum A {
    P(*const c_void),
    I(i32),
    L(i64),
}

/// Launch `name` (recorded under `key`) with the given dynamic shared memory; errors are dropped,
/// as the C `<<<>>>` drops them. `smem > 0` first raises the kernel's dynamic shared-memory limit
/// (CUDA_SET_SHARED_MEMORY_LIMIT, also unchecked).
unsafe fn launch(key: String, name: &str, grid: (u32, u32, u32), block: (u32, u32, u32), smem: u32, stream: *mut c_void, args: &[A]) {
    unsafe {
        let s = stream as sys::CUstream;
        let f = function(name, s);
        let ls = if s.is_null() { PER_THREAD as sys::CUstream } else { s };
        let mut vals: Vec<u64> = args
            .iter()
            .map(|a| match *a {
                A::P(p) => p as u64,
                A::I(v) => v as u32 as u64,
                A::L(v) => v as u64,
            })
            .collect();
        let mut ptrs: Vec<*mut c_void> = vals.iter_mut().map(|v| v as *mut u64 as *mut c_void).collect();
        record(key);
        sys::cuLaunchKernel(f, grid.0, grid.1, grid.2, block.0, block.1, block.2, smem, ls, ptrs.as_mut_ptr(), std::ptr::null_mut());
    }
}

// ================================================================================================
// mmvq_gguf.cu

const TYPES: [&str; 10] = ["q4_0", "q4_1", "q5_0", "q5_1", "q8_0", "q2_k", "q3_k", "q4_k", "q5_k", "q6_k"];

fn kname(q: &str, d: &str, kind: &str, b: i32) -> String {
    format!("mmvq_gguf_{q}_{d}_{kind}_cuda{b}")
}

/// `MMVQ_LAUNCHER_PLAIN`: 2 rows per block, (8 | 4 | 2) warps for b_size (1 | <= 4 | else).
unsafe fn plain(
    q: &str, d: &str, vx: *const c_void, vy: *const c_void, dst: *mut c_void, ncols_x: i32, nrows_x: i32,
    stride_col_y: i32, stride_col_dst: i32, b_size: i32, stream: *mut c_void,
) {
    let rows_per_block: u32 = 2;
    let nblocks = (nrows_x as u32).wrapping_add(rows_per_block - 1) / rows_per_block;
    let nwarps: u32 = if b_size == 1 {
        8
    } else if b_size <= 4 {
        4
    } else {
        2
    };
    if !(1..=8).contains(&b_size) {
        return;
    }
    let n = kname(q, d, "plain", b_size);
    unsafe {
        launch(n.clone(), &n, (nblocks, 1, 1), (32, nwarps, 1), 0, stream, &[
            A::P(vx), A::P(vy), A::P(dst), A::I(ncols_x), A::I(nrows_x), A::I(stride_col_y), A::I(stride_col_dst),
        ])
    }
}

/// `MMVQ_LAUNCHER_FUSED_GLU`: rows 2 (b_size <= 1) / 1 (<= 4) / 2, warps 4 (b_size == 1) / 2.
unsafe fn fused_glu(
    q: &str, d: &str, vx_gate: *const c_void, vx_up: *const c_void, vy: *const c_void, dst: *mut c_void, ncols_x: i32,
    nrows_x: i32, stride_col_y: i32, stride_col_dst: i32, b_size: i32, activation: i32, stream: *mut c_void,
) {
    let rows_per_block: u32 = if b_size <= 1 {
        2
    } else if b_size <= 4 {
        1
    } else {
        2
    };
    let nblocks = (nrows_x as u32).wrapping_add(rows_per_block - 1) / rows_per_block;
    let nwarps: u32 = if b_size == 1 { 4 } else { 2 };
    if !(1..=8).contains(&b_size) {
        return;
    }
    let n = kname(q, d, "fused_glu", b_size);
    unsafe {
        launch(n.clone(), &n, (nblocks, 1, 1), (32, nwarps, 1), 0, stream, &[
            A::P(vx_gate), A::P(vx_up), A::P(vy), A::P(dst), A::I(ncols_x), A::I(nrows_x), A::I(stride_col_y),
            A::I(stride_col_dst), A::I(activation),
        ])
    }
}

/// `MMVQ_LAUNCHER_FUSED_QKV`: 2 rows per block; blocks packed along x when the largest matrix has
/// at least twice the rows of the smallest, else one grid row (blockIdx.y) per matrix.
unsafe fn fused_qkv(
    q: &str, d: &str, vx_q: *const c_void, vx_k: *const c_void, vx_v: *const c_void, vy: *const c_void, q_dst: *mut c_void,
    k_dst: *mut c_void, v_dst: *mut c_void, ncols_x: i32, nrows_q: i32, nrows_k: i32, nrows_v: i32, stride_col_y: i32,
    b_size: i32, stream: *mut c_void,
) {
    let rows_per_block: u32 = 2;
    let mut max_nrows = if nrows_q > nrows_k { nrows_q } else { nrows_k };
    max_nrows = if max_nrows > nrows_v { max_nrows } else { nrows_v };
    let mut min_nrows = if nrows_q < nrows_k { nrows_q } else { nrows_k };
    min_nrows = if min_nrows < nrows_v { min_nrows } else { nrows_v };
    let use_packed = max_nrows >= 2i32.wrapping_mul(min_nrows);
    let blocks = |n: i32| (n as u32).wrapping_add(rows_per_block - 1) / rows_per_block;
    let (qb, kb, vb) = (blocks(nrows_q), blocks(nrows_k), blocks(nrows_v));
    let nblocks = if use_packed { qb.wrapping_add(kb).wrapping_add(vb) } else { blocks(max_nrows) };
    let nwarps: u32 = if b_size == 1 {
        8
    } else if b_size <= 4 {
        4
    } else {
        2
    };
    if !(1..=8).contains(&b_size) {
        return;
    }
    let n = kname(q, d, "fused_qkv", b_size);
    unsafe {
        launch(n.clone(), &n, (nblocks, if use_packed { 1 } else { 3 }, 1), (32, nwarps, 1), 0, stream, &[
            A::P(vx_q), A::P(vx_k), A::P(vx_v), A::P(vy), A::P(q_dst), A::P(k_dst), A::P(v_dst), A::I(ncols_x),
            A::I(nrows_q), A::I(nrows_k), A::I(nrows_v), A::I(stride_col_y),
        ])
    }
}

macro_rules! mmvq_launchers {
    ($($plain:ident, $glu:ident, $qkv:ident, $q:literal, $d:literal;)*) => {$(
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $plain(
            vx: *const c_void, vy: *const c_void, dst: *mut c_void, ncols_x: i32, nrows_x: i32,
            stride_col_y: i32, stride_col_dst: i32, b_size: i32, stream: *mut c_void,
        ) {
            unsafe { plain($q, $d, vx, vy, dst, ncols_x, nrows_x, stride_col_y, stride_col_dst, b_size, stream) }
        }
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $glu(
            vx_gate: *const c_void, vx_up: *const c_void, vy: *const c_void, dst: *mut c_void, ncols_x: i32, nrows_x: i32,
            stride_col_y: i32, stride_col_dst: i32, b_size: i32, activation: i32, stream: *mut c_void,
        ) {
            unsafe { fused_glu($q, $d, vx_gate, vx_up, vy, dst, ncols_x, nrows_x, stride_col_y, stride_col_dst, b_size, activation, stream) }
        }
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $qkv(
            vx_q: *const c_void, vx_k: *const c_void, vx_v: *const c_void, vy: *const c_void, q_dst: *mut c_void,
            k_dst: *mut c_void, v_dst: *mut c_void, ncols_x: i32, nrows_q: i32, nrows_k: i32, nrows_v: i32,
            stride_col_y: i32, b_size: i32, stream: *mut c_void,
        ) {
            unsafe { fused_qkv($q, $d, vx_q, vx_k, vx_v, vy, q_dst, k_dst, v_dst, ncols_x, nrows_q, nrows_k, nrows_v, stride_col_y, b_size, stream) }
        }
    )*};
}

mmvq_launchers! {
    launch_mmvq_gguf_q4_0_bf16_plain, launch_mmvq_gguf_q4_0_bf16_fused_glu, launch_mmvq_gguf_q4_0_bf16_fused_qkv, "q4_0", "bf16";
    launch_mmvq_gguf_q4_1_bf16_plain, launch_mmvq_gguf_q4_1_bf16_fused_glu, launch_mmvq_gguf_q4_1_bf16_fused_qkv, "q4_1", "bf16";
    launch_mmvq_gguf_q5_0_bf16_plain, launch_mmvq_gguf_q5_0_bf16_fused_glu, launch_mmvq_gguf_q5_0_bf16_fused_qkv, "q5_0", "bf16";
    launch_mmvq_gguf_q5_1_bf16_plain, launch_mmvq_gguf_q5_1_bf16_fused_glu, launch_mmvq_gguf_q5_1_bf16_fused_qkv, "q5_1", "bf16";
    launch_mmvq_gguf_q8_0_bf16_plain, launch_mmvq_gguf_q8_0_bf16_fused_glu, launch_mmvq_gguf_q8_0_bf16_fused_qkv, "q8_0", "bf16";
    launch_mmvq_gguf_q2_k_bf16_plain, launch_mmvq_gguf_q2_k_bf16_fused_glu, launch_mmvq_gguf_q2_k_bf16_fused_qkv, "q2_k", "bf16";
    launch_mmvq_gguf_q3_k_bf16_plain, launch_mmvq_gguf_q3_k_bf16_fused_glu, launch_mmvq_gguf_q3_k_bf16_fused_qkv, "q3_k", "bf16";
    launch_mmvq_gguf_q4_k_bf16_plain, launch_mmvq_gguf_q4_k_bf16_fused_glu, launch_mmvq_gguf_q4_k_bf16_fused_qkv, "q4_k", "bf16";
    launch_mmvq_gguf_q5_k_bf16_plain, launch_mmvq_gguf_q5_k_bf16_fused_glu, launch_mmvq_gguf_q5_k_bf16_fused_qkv, "q5_k", "bf16";
    launch_mmvq_gguf_q6_k_bf16_plain, launch_mmvq_gguf_q6_k_bf16_fused_glu, launch_mmvq_gguf_q6_k_bf16_fused_qkv, "q6_k", "bf16";
    launch_mmvq_gguf_q4_0_f16_plain, launch_mmvq_gguf_q4_0_f16_fused_glu, launch_mmvq_gguf_q4_0_f16_fused_qkv, "q4_0", "f16";
    launch_mmvq_gguf_q4_1_f16_plain, launch_mmvq_gguf_q4_1_f16_fused_glu, launch_mmvq_gguf_q4_1_f16_fused_qkv, "q4_1", "f16";
    launch_mmvq_gguf_q5_0_f16_plain, launch_mmvq_gguf_q5_0_f16_fused_glu, launch_mmvq_gguf_q5_0_f16_fused_qkv, "q5_0", "f16";
    launch_mmvq_gguf_q5_1_f16_plain, launch_mmvq_gguf_q5_1_f16_fused_glu, launch_mmvq_gguf_q5_1_f16_fused_qkv, "q5_1", "f16";
    launch_mmvq_gguf_q8_0_f16_plain, launch_mmvq_gguf_q8_0_f16_fused_glu, launch_mmvq_gguf_q8_0_f16_fused_qkv, "q8_0", "f16";
    launch_mmvq_gguf_q2_k_f16_plain, launch_mmvq_gguf_q2_k_f16_fused_glu, launch_mmvq_gguf_q2_k_f16_fused_qkv, "q2_k", "f16";
    launch_mmvq_gguf_q3_k_f16_plain, launch_mmvq_gguf_q3_k_f16_fused_glu, launch_mmvq_gguf_q3_k_f16_fused_qkv, "q3_k", "f16";
    launch_mmvq_gguf_q4_k_f16_plain, launch_mmvq_gguf_q4_k_f16_fused_glu, launch_mmvq_gguf_q4_k_f16_fused_qkv, "q4_k", "f16";
    launch_mmvq_gguf_q5_k_f16_plain, launch_mmvq_gguf_q5_k_f16_fused_glu, launch_mmvq_gguf_q5_k_f16_fused_qkv, "q5_k", "f16";
    launch_mmvq_gguf_q6_k_f16_plain, launch_mmvq_gguf_q6_k_f16_fused_glu, launch_mmvq_gguf_q6_k_f16_fused_qkv, "q6_k", "f16";
    launch_mmvq_gguf_q4_0_f32_plain, launch_mmvq_gguf_q4_0_f32_fused_glu, launch_mmvq_gguf_q4_0_f32_fused_qkv, "q4_0", "f32";
    launch_mmvq_gguf_q4_1_f32_plain, launch_mmvq_gguf_q4_1_f32_fused_glu, launch_mmvq_gguf_q4_1_f32_fused_qkv, "q4_1", "f32";
    launch_mmvq_gguf_q5_0_f32_plain, launch_mmvq_gguf_q5_0_f32_fused_glu, launch_mmvq_gguf_q5_0_f32_fused_qkv, "q5_0", "f32";
    launch_mmvq_gguf_q5_1_f32_plain, launch_mmvq_gguf_q5_1_f32_fused_glu, launch_mmvq_gguf_q5_1_f32_fused_qkv, "q5_1", "f32";
    launch_mmvq_gguf_q8_0_f32_plain, launch_mmvq_gguf_q8_0_f32_fused_glu, launch_mmvq_gguf_q8_0_f32_fused_qkv, "q8_0", "f32";
    launch_mmvq_gguf_q2_k_f32_plain, launch_mmvq_gguf_q2_k_f32_fused_glu, launch_mmvq_gguf_q2_k_f32_fused_qkv, "q2_k", "f32";
    launch_mmvq_gguf_q3_k_f32_plain, launch_mmvq_gguf_q3_k_f32_fused_glu, launch_mmvq_gguf_q3_k_f32_fused_qkv, "q3_k", "f32";
    launch_mmvq_gguf_q4_k_f32_plain, launch_mmvq_gguf_q4_k_f32_fused_glu, launch_mmvq_gguf_q4_k_f32_fused_qkv, "q4_k", "f32";
    launch_mmvq_gguf_q5_k_f32_plain, launch_mmvq_gguf_q5_k_f32_fused_glu, launch_mmvq_gguf_q5_k_f32_fused_qkv, "q5_k", "f32";
    launch_mmvq_gguf_q6_k_f32_plain, launch_mmvq_gguf_q6_k_f32_fused_glu, launch_mmvq_gguf_q6_k_f32_fused_qkv, "q6_k", "f32";
}

/// Quantize launchers: grid ((kx_padded + 255) / 256, num_rows), block 256.
unsafe fn mmvq_quantize(t: &str, x: *const c_void, vy: *mut c_void, kx: i32, kx_padded: i32, num_rows: i32, stream: *mut c_void) {
    let num_blocks_x = kx_padded.wrapping_add(255) / 256;
    let n = format!("mmvq_gguf_quantize_q8_1_{t}");
    unsafe {
        launch(n.clone(), &n, (num_blocks_x as u32, num_rows as u32, 1), (256, 1, 1), 0, stream, &[
            A::P(x), A::P(vy), A::I(kx), A::I(kx_padded),
        ])
    }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn launch_mmvq_gguf_quantize_q8_1_bf16(x: *const c_void, vy: *mut c_void, kx: i32, kx_padded: i32, num_rows: i32, stream: *mut c_void) {
    unsafe { mmvq_quantize("bf16", x, vy, kx, kx_padded, num_rows, stream) }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn launch_mmvq_gguf_quantize_q8_1_f16(x: *const c_void, vy: *mut c_void, kx: i32, kx_padded: i32, num_rows: i32, stream: *mut c_void) {
    unsafe { mmvq_quantize("f16", x, vy, kx, kx_padded, num_rows, stream) }
}
#[unsafe(no_mangle)]
pub unsafe extern "C" fn launch_mmvq_gguf_quantize_q8_1_f32(x: *const c_void, vy: *mut c_void, kx: i32, kx_padded: i32, num_rows: i32, stream: *mut c_void) {
    unsafe { mmvq_quantize("f32", x, vy, kx, kx_padded, num_rows, stream) }
}

#[allow(dead_code)]
pub fn types() -> &'static [&'static str; 10] {
    &TYPES
}

// ================================================================================================
// mmq_quantize.cu

/// `launch_mmq_quantize_q8_1_typed<layout>`: grid (ne1, ceil(ne0 / 512), ne2*ne3), 128 threads;
/// type_x 0 = f32, 1 = f16, 30 = bf16, anything else launches nothing.
unsafe fn mmq_quantize(
    layout: &str, x: *const c_void, ids: *const i32, vy: *mut c_void, type_x: i32, ne00: i64, s01: i64, s02: i64, s03: i64,
    ne0: i64, ne1: i64, ne2: i64, ne3: i64, stream: *mut c_void,
) {
    let block_num_y = (ne0 + 4 * 128 - 1) / (4 * 128);
    let grid = (ne1 as u32, block_num_y as u32, ne2.wrapping_mul(ne3) as u32);
    let t = match type_x {
        0 => "f32",
        1 => "f16",
        30 => "bf16",
        _ => return,
    };
    let n = format!("quantize_mmq_q8_1_{t}_{layout}");
    unsafe {
        launch(n.clone(), &n, grid, (128, 1, 1), 0, stream, &[
            A::P(x), A::P(ids as *const c_void), A::P(vy), A::L(ne00), A::L(s01), A::L(s02), A::L(s03), A::L(ne0), A::I(ne1 as i32),
            A::I(ne2 as i32),
        ]);
    }
}

macro_rules! mmq_quantize_launcher {
    ($fn:ident, $l:literal) => {
        #[allow(non_snake_case)]
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $fn(
            x: *const c_void, ids: *const i32, vy: *mut c_void, type_x: i32, ne00: i64, s01: i64, s02: i64, s03: i64, ne0: i64,
            ne1: i64, ne2: i64, ne3: i64, stream: *mut c_void,
        ) {
            unsafe { mmq_quantize($l, x, ids, vy, type_x, ne00, s01, s02, s03, ne0, ne1, ne2, ne3, stream) }
        }
    };
}
mmq_quantize_launcher!(launch_mmq_quantize_q8_1_D4, "d4");
mmq_quantize_launcher!(launch_mmq_quantize_q8_1_DS4, "ds4");
mmq_quantize_launcher!(launch_mmq_quantize_q8_1_D2S6, "d2s6");

/// `launch_mmq_quantize_glu_q8_1_f32_typed<layout>`: grid (ne1, ceil(ne0 / 512), 1), 128 threads.
unsafe fn mmq_quantize_glu(
    layout: &str, gate: *const f32, up: *const f32, ids: *const i32, vy: *mut c_void, ne00: i64, s01: i64, ne0: i64, ne1: i64,
    activation: i32, stream: *mut c_void,
) {
    let block_num_y = (ne0 + 4 * 128 - 1) / (4 * 128);
    let n = format!("quantize_mmq_q8_1_glu_f32_{layout}");
    unsafe {
        launch(n.clone(), &n, (ne1 as u32, block_num_y as u32, 1), (128, 1, 1), 0, stream, &[
            A::P(gate as *const c_void), A::P(up as *const c_void), A::P(ids as *const c_void), A::P(vy), A::L(ne00), A::L(s01),
            A::L(ne0), A::I(ne1 as i32), A::I(activation),
        ]);
    }
}

macro_rules! mmq_quantize_glu_launcher {
    ($fn:ident, $l:literal) => {
        #[allow(non_snake_case)]
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $fn(
            gate: *const f32, up: *const f32, ids: *const i32, vy: *mut c_void, ne00: i64, s01: i64, ne0: i64, ne1: i64,
            activation: i32, stream: *mut c_void,
        ) {
            unsafe { mmq_quantize_glu($l, gate, up, ids, vy, ne00, s01, ne0, ne1, activation, stream) }
        }
    };
}
mmq_quantize_glu_launcher!(launch_mmq_quantize_glu_q8_1_D4_f32, "d4");
mmq_quantize_glu_launcher!(launch_mmq_quantize_glu_q8_1_DS4_f32, "ds4");
mmq_quantize_glu_launcher!(launch_mmq_quantize_glu_q8_1_D2S6_f32, "d2s6");

/// `launch_mmq_quantize_glu_q8_1_typed<layout>`: the void-pointer entry of the C++ (dense GGUF
/// prefill), dispatching on `type_x` (GGML_TYPE 0 f32, 1 f16, 30 bf16). Same grid and block as the
/// f32 launcher; an unlisted `type_x` launches nothing, as the C++ `default:` does.
unsafe fn mmq_quantize_glu_typed(
    layout: &str, gate: *const c_void, up: *const c_void, ids: *const i32, vy: *mut c_void, type_x: i32, ne00: i64, s01: i64, ne0: i64,
    ne1: i64, activation: i32, stream: *mut c_void,
) {
    let tn = match type_x {
        0 => "f32",
        1 => "f16",
        30 => "bf16",
        _ => return,
    };
    let block_num_y = (ne0 + 4 * 128 - 1) / (4 * 128);
    let n = format!("quantize_mmq_q8_1_glu_{tn}_{layout}");
    unsafe {
        launch(n.clone(), &n, (ne1 as u32, block_num_y as u32, 1), (128, 1, 1), 0, stream, &[
            A::P(gate), A::P(up), A::P(ids as *const c_void), A::P(vy), A::L(ne00), A::L(s01),
            A::L(ne0), A::I(ne1 as i32), A::I(activation),
        ]);
    }
}

macro_rules! mmq_quantize_glu_typed_launcher {
    ($fn:ident, $l:literal) => {
        #[allow(non_snake_case)]
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $fn(
            gate: *const c_void, up: *const c_void, ids: *const i32, vy: *mut c_void, type_x: i32, ne00: i64, s01: i64, ne0: i64,
            ne1: i64, activation: i32, stream: *mut c_void,
        ) {
            unsafe { mmq_quantize_glu_typed($l, gate, up, ids, vy, type_x, ne00, s01, ne0, ne1, activation, stream) }
        }
    };
}
mmq_quantize_glu_typed_launcher!(launch_mmq_quantize_glu_q8_1_D4, "d4");
mmq_quantize_glu_typed_launcher!(launch_mmq_quantize_glu_q8_1_DS4, "ds4");
mmq_quantize_glu_typed_launcher!(launch_mmq_quantize_glu_q8_1_D2S6, "d2s6");

// ================================================================================================
// mmq_instance_*.cu (+ the host helpers of mmq_common.cuh / mmq_gguf.cuh), for the sm_120a build:
// `__CUDA_ARCH_LIST__` = 1200, so ggml_cuda_highest_compiled_arch(cc) is 1200 for cc >= 1200 and
// -1 below.

const MAX_CPY_OFFSET_MTHREADS: i32 = 0x0100000;
fn is_nvidia(cc: i32) -> bool {
    cc < MAX_CPY_OFFSET_MTHREADS
}
fn highest_compiled_arch(cc: i32) -> i32 {
    if 1200 <= cc { 1200 } else { -1 }
}
fn turing_mma_available(cc: i32) -> bool {
    is_nvidia(cc) && highest_compiled_arch(cc) >= 750
}
fn volta_plus(cc: i32) -> bool {
    is_nvidia(cc) && highest_compiled_arch(cc) >= 700
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Ty {
    Q4_0,
    Q4_1,
    Q5_0,
    Q5_1,
    Q8_0,
    Q2K,
    Q3K,
    Q4K,
    Q5K,
    Q6K,
}

impl Ty {
    fn name(self) -> &'static str {
        TYPES[self as usize]
    }
    fn qk(self) -> i32 {
        match self {
            Ty::Q2K | Ty::Q3K | Ty::Q4K | Ty::Q5K | Ty::Q6K => 256,
            _ => 32,
        }
    }
    /// mmq_get_mma_tile_x_k.
    fn mma_tile_x_k(self) -> i64 {
        match self {
            Ty::Q2K => 100,
            Ty::Q3K => 84,
            _ => 76,
        }
    }
    /// mmq_get_dp4a_tile_x_sizes (qs, dm, sc).
    fn dp4a_txs(self, mmq_y: i64) -> (i64, i64, i64) {
        const K: i64 = 32;
        let q8_0 = (mmq_y * K * 2 + mmq_y, mmq_y * K * 2 / 8 + mmq_y / (8 / 2), 0);
        match self {
            Ty::Q4_0 | Ty::Q4_1 => (mmq_y * K + mmq_y, mmq_y * K / 4 + mmq_y / 4, 0),
            Ty::Q5_0 | Ty::Q8_0 => q8_0,
            Ty::Q5_1 => (mmq_y * K * 2 + mmq_y, mmq_y * K * 2 / 8 + mmq_y / (8 / 2), 0),
            Ty::Q2K => (mmq_y * K * 2 + mmq_y, mmq_y * K + mmq_y, 0),
            Ty::Q3K => (mmq_y * K * 2 + mmq_y, mmq_y, mmq_y * K / 8 + mmq_y / 8),
            Ty::Q4K => (mmq_y * K + mmq_y, mmq_y * K / 32, mmq_y * K / 8 + mmq_y / 8),
            Ty::Q5K => (mmq_y * K * 2 + mmq_y, mmq_y * K / 32 + mmq_y / 32, mmq_y * K / 8 + mmq_y / 8),
            Ty::Q6K => (mmq_y * K * 2 + mmq_y, mmq_y * K / 32 + mmq_y / 32, mmq_y * K / 8 + mmq_y / 8),
        }
    }
}

/// mmq_get_nbytes_shared<type> (size_t arithmetic).
fn nbytes_shared(t: Ty, mmq_x: i32, mmq_y: i32, cc: i32, warp_size: i32, nwarps: i32) -> u64 {
    let (qs, dm, sc) = t.dp4a_txs(mmq_y as i64);
    let nbs_ids = (mmq_x as i64 as u64).wrapping_mul(4);
    let nbs_x = if turing_mma_available(cc) {
        ((mmq_y as i64 * t.mma_tile_x_k()) as u64).wrapping_mul(4)
    } else {
        (qs as u64).wrapping_mul(4).wrapping_add((dm as u64).wrapping_mul(4)).wrapping_add((sc as u64).wrapping_mul(4))
    };
    let nbs_y = (mmq_x as i64 as u64).wrapping_mul(144);
    let n = ((nwarps.wrapping_mul(warp_size)) as i64 as u64).wrapping_mul(4);
    let pad = (nbs_y.wrapping_add(n).wrapping_sub(1)) & !(n.wrapping_sub(1));
    nbs_ids.wrapping_add(nbs_x).wrapping_add(pad)
}

/// GGML_ASSERT (host): print to stderr and abort.
fn ggml_assert(ok: bool, what: &str) {
    if !ok {
        eprintln!("GGML_ASSERT failed: {what}");
        std::process::abort();
    }
}

/// init_fastdiv_values(uint64_t d): <mp, L, d>.
fn fastdiv_values(d_64: u64) -> [u32; 3] {
    ggml_assert(d_64 != 0, "d_64 != 0");
    ggml_assert(d_64 <= u32::MAX as u64, "d_64 <= std::numeric_limits<uint32_t>::max()");
    let d = d_64 as u32;
    let mut l: u32 = 0;
    while l < 32 && (1u32 << l) < d {
        l += 1;
    }
    let mp = (((1u64 << 32) * ((1u64 << l) - d as u64)) / d as u64 + 1) as u32;
    [mp, l, d]
}

/// mmq_args.
#[derive(Clone, Copy)]
struct MmqArgs {
    x: *const c_void,
    y: *const c_void,
    ids_dst: *const i32,
    expert_bounds: *const i32,
    dst: *mut c_void,
    type_dst: i32,
    ncols_x: i64,
    nrows_x: i64,
    ncols_dst: i64,
    stride_row_x: i64,
    ncols_y: i64,
    nrows_dst: i64,
    nchannels_x: i64,
    nchannels_y: i64,
    stride_channel_x: i64,
    stride_channel_y: i64,
    stride_channel_dst: i64,
    nsamples_x: i64,
    nsamples_y: i64,
    stride_sample_x: i64,
    stride_sample_y: i64,
    stride_sample_dst: i64,
    use_stream_k: bool,
    ncols_max: i64,
}

/// CUDA_SET_SHARED_MEMORY_LIMIT: raised once per kernel instance and device, with the first size.
static RAISED: Mutex<Option<HashSet<(String, usize)>>> = Mutex::new(None);

unsafe fn set_shared_limit(name: &str, nbytes: i32, stream: *mut c_void) {
    unsafe {
        let s = stream as sys::CUstream;
        let ctx = stream_context(s) as usize;
        let mut g = RAISED.lock().unwrap();
        let set = g.get_or_insert_with(HashSet::new);
        if set.insert((name.to_string(), ctx)) {
            let f = function(name, s);
            sys::cuFuncSetAttribute(f, sys::CUfunction_attribute_enum_CU_FUNC_ATTRIBUTE_MAX_DYNAMIC_SHARED_SIZE_BYTES, nbytes);
        }
    }
}

/// instantiate_mmq_<type><mmq_x>.
unsafe fn instantiate(t: Ty, mmq_x: i32, tmp_fixup: *mut f32, a: &MmqArgs, stream: *mut c_void, cc: i32, nsm: i32, warp_size: i32) {
    let mmq_y: i32 = if volta_plus(cc) { 128 } else { 64 };
    let nwarps = 256 / warp_size;
    let nbytes = nbytes_shared(t, mmq_x, mmq_y, cc, warp_size, nwarps) as i32;
    let nty = ((a.nrows_x + mmq_y as i64 - 1) / mmq_y as i64) as i32;
    let ntx = ((a.ncols_max + mmq_x as i64 - 1) / mmq_x as i64) as i32;
    let ntzw = a.nchannels_y.wrapping_mul(a.nsamples_y) as i32;
    let block = (warp_size as u32, nwarps as u32, 1u32);
    let channel_ratio = (a.nchannels_y / a.nchannels_x) as i32;
    let sample_ratio = (a.nsamples_y / a.nsamples_x) as i32;

    let bpn = fastdiv_values((a.ncols_x / t.qk() as i64) as u64);
    let ntx_fd = fastdiv_values(ntx as i64 as u64);
    let ncy = fastdiv_values(a.nchannels_y as u64);
    let nsy = fastdiv_values(a.nsamples_y as u64);
    let cr = fastdiv_values(channel_ratio as i64 as u64);
    let sr = fastdiv_values(sample_ratio as i64 as u64);

    let names = [0, 1].map(|nc| format!("mmq_{}_x{mmq_x}_nc{nc}", t.name()));
    unsafe {
        set_shared_limit(&names[0], nbytes, stream);
        set_shared_limit(&names[1], nbytes, stream);
    }
    let fd = |v: [u32; 3]| [A::I(v[0] as i32), A::I(v[1] as i32), A::I(v[2] as i32)];
    let main_args = |fixup: *mut f32| -> Vec<A> {
        let mut v = vec![
            A::P(a.x), A::P(a.y), A::P(a.ids_dst as *const c_void), A::P(a.expert_bounds as *const c_void), A::P(a.dst),
            A::P(fixup as *const c_void),
        ];
        v.extend(fd(bpn));
        v.extend([A::I(a.nrows_x as i32), A::I(a.ncols_dst as i32), A::I(a.stride_row_x as i32), A::I(a.ncols_y as i32), A::I(a.nrows_dst as i32)]);
        v.extend(fd(cr));
        v.extend(fd(ncy));
        v.extend([A::I(a.stride_channel_x as i32), A::I(a.stride_channel_y as i32), A::I(a.stride_channel_dst as i32)]);
        v.extend(fd(sr));
        v.extend(fd(nsy));
        v.extend([A::I(a.stride_sample_x as i32), A::I(a.stride_sample_y as i32), A::I(a.stride_sample_dst as i32), A::I(a.type_dst)]);
        v.extend(fd(ntx_fd));
        v
    };
    let nc = (a.nrows_x % mmq_y as i64 != 0) as usize;
    unsafe {
        if !a.use_stream_k {
            launch(names[nc].clone(), &names[nc], (nty as u32, ntx as u32, ntzw as u32), block, nbytes as u32, stream, &main_args(std::ptr::null_mut()));
            return;
        }
        let ntiles_dst = ntx.wrapping_mul(nty).wrapping_mul(ntzw);
        let tiles_nwaves = ntiles_dst.wrapping_add(nsm - 1) / nsm;
        let eff = 100i32.wrapping_mul(ntiles_dst) / nsm.wrapping_mul(tiles_nwaves);
        let grid_sk_x: u32 = if is_nvidia(cc) && eff >= 90 { ntiles_dst as u32 } else { nsm as u32 };
        let fixup_needed = (ntiles_dst as u32) % grid_sk_x != 0;
        ggml_assert((ntiles_dst as u32).wrapping_mul(bpn[2]) < (1u32 << 30), "ntiles_dst * blocks_per_ne00_fd.z < (1 << 30)");
        launch(names[nc].clone(), &names[nc], (grid_sk_x, 1, 1), block, nbytes as u32, stream, &main_args(tmp_fixup));
        if fixup_needed {
            let fname = format!("mmq_fixup_qk{}_x{mmq_x}_nc{nc}", t.qk());
            let key = format!("mmq_fixup_{}_x{mmq_x}_nc{nc}", t.name());
            let mut v = vec![A::P(a.ids_dst as *const c_void), A::P(a.expert_bounds as *const c_void), A::P(a.dst), A::I(a.type_dst),
                             A::P(tmp_fixup as *const c_void)];
            v.extend(fd(bpn));
            v.extend([A::I(a.nrows_x as i32), A::I(a.ncols_dst as i32), A::I(a.nrows_dst as i32)]);
            v.extend(fd(ncy));
            v.push(A::I(a.stride_channel_dst as i32));
            v.extend(fd(nsy));
            v.push(A::I(a.stride_sample_dst as i32));
            v.extend(fd(ntx_fd));
            launch(key, &fname, (grid_sk_x, (mmq_y / warp_size) as u32, 1), (block.0, block.1 / 2, 1), 0, stream, &v);
        }
    }
}

/// launch_mmq_case_<type>: pick the tile width mmq_x with the fewest column tiles that fits the
/// shared-memory budget, then instantiate it.
unsafe fn launch_case(t: Ty, tmp_fixup: *mut f32, a: &MmqArgs, stream: *mut c_void, cc: i32, nsm: i32, smpbo: i64, warp_size: i32) {
    let mmq_x_max = if turing_mma_available(cc) { 128 } else { 64 };
    let mmq_y: i32 = if volta_plus(cc) { 128 } else { 64 };
    let nwarps = 256 / warp_size;
    let smpbo = smpbo as u64; // size_t parameter
    let mut mmq_x_best = 0;
    let mut ntiles_x_best = i32::MAX;
    let mut mmq_x = 8;
    while mmq_x <= mmq_x_max && ntiles_x_best > 1 {
        let granularity = if turing_mma_available(cc) && mmq_x >= 48 { 16 } else { 8 };
        if mmq_x % granularity == 0 && nbytes_shared(t, mmq_x, mmq_y, cc, warp_size, nwarps) <= smpbo {
            let ntiles_x = ((a.ncols_max + mmq_x as i64 - 1) / mmq_x as i64) as i32;
            if ntiles_x < ntiles_x_best {
                mmq_x_best = mmq_x;
                ntiles_x_best = ntiles_x;
            }
        }
        mmq_x += 8;
    }
    if mmq_x_best % 8 != 0 || !(8..=128).contains(&mmq_x_best) {
        return;
    }
    unsafe { instantiate(t, mmq_x_best, tmp_fixup, a, stream, cc, nsm, warp_size) }
}

/// launch_mmq_gguf_<type>: dense matmul, dst column stride nrows_x (stride_col_dst is ignored).
unsafe fn mmq_dense(
    t: Ty, tmp_fixup: *mut c_void, x: *const c_void, y: *const c_void, dst: *mut c_void, ncols_x: i64, nrows_x: i64, ncols_y: i64,
    stride_row_x: i64, cc: i32, nsm: i32, smpbo: i64, warp_size: i32, type_dst: i32, stream: *mut c_void,
) {
    let a = MmqArgs {
        x, y, ids_dst: std::ptr::null(), expert_bounds: std::ptr::null(), dst, type_dst, ncols_x, nrows_x, ncols_dst: ncols_y, stride_row_x,
        ncols_y, nrows_dst: nrows_x, nchannels_x: 1, nchannels_y: 1, stride_channel_x: 0, stride_channel_y: 0, stride_channel_dst: 0,
        nsamples_x: 1, nsamples_y: 1, stride_sample_x: 0, stride_sample_y: 0, stride_sample_dst: 0, use_stream_k: volta_plus(cc),
        ncols_max: ncols_y,
    };
    unsafe { launch_case(t, tmp_fixup as *mut f32, &a, stream, cc, nsm, smpbo, warp_size) }
}

/// launch_mmq_gguf_<type>_moe (DEFINE_MMQ_MOE_LAUNCHER): one channel per expert, rows of expert e
/// are y columns expert_bounds[e]..expert_bounds[e+1], written to dst column ids_dst[..]; f32 dst.
unsafe fn mmq_moe(
    t: Ty, tmp_fixup: *mut c_void, x: *const c_void, y: *const c_void, ids_dst: *const i32, expert_bounds: *const i32, dst: *mut c_void,
    ncols_x: i64, nrows_x: i64, ncols_dst: i64, stride_row_x: i64, stride_col_dst: i64, num_experts: i64, ncols_max: i64, cc: i32,
    nsm: i32, smpbo: i64, warp_size: i32, stream: *mut c_void,
) {
    // dst column stride = stride_col_dst, as DEFINE_MMQ_MOE_LAUNCHER passes it (nrows_dst); the dense launcher
    // ignores its stride_col_dst, the MoE one does not (gate/up packed into one buffer use 2 * nrows).
    let a = MmqArgs {
        x, y, ids_dst, expert_bounds, dst, type_dst: 0, ncols_x, nrows_x, ncols_dst, stride_row_x, ncols_y: ncols_dst, nrows_dst: stride_col_dst,
        nchannels_x: num_experts, nchannels_y: num_experts, stride_channel_x: nrows_x.wrapping_mul(stride_row_x), stride_channel_y: 0,
        stride_channel_dst: 0, nsamples_x: 1, nsamples_y: 1, stride_sample_x: 0, stride_sample_y: 0, stride_sample_dst: 0,
        use_stream_k: volta_plus(cc), ncols_max,
    };
    unsafe { launch_case(t, tmp_fixup as *mut f32, &a, stream, cc, nsm, smpbo, warp_size) }
}

macro_rules! mmq_launchers {
    ($($dense:ident, $moe:ident, $t:expr;)*) => {$(
        /// Same signature and launch logic as the mistralrs-quant C launcher of this name.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $dense(
            tmp_fixup: *mut c_void, x: *const c_void, y: *const c_void, dst: *mut c_void, ncols_x: i64, nrows_x: i64, ncols_y: i64,
            stride_row_x: i64, _stride_col_dst: i64, cc: i32, nsm: i32, smpbo: i64, warp_size: i32, type_dst: i32, stream: *mut c_void,
        ) {
            unsafe { mmq_dense($t, tmp_fixup, x, y, dst, ncols_x, nrows_x, ncols_y, stride_row_x, cc, nsm, smpbo, warp_size, type_dst, stream) }
        }
        /// Same signature and launch logic as the mistralrs-quant C launcher of this name.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $moe(
            tmp_fixup: *mut c_void, x: *const c_void, y: *const c_void, ids_dst: *const i32, expert_bounds: *const i32, dst: *mut c_void,
            ncols_x: i64, nrows_x: i64, ncols_dst: i64, stride_row_x: i64, stride_col_dst: i64, num_experts: i64, ncols_max: i64,
            cc: i32, nsm: i32, smpbo: i64, warp_size: i32, stream: *mut c_void,
        ) {
            unsafe {
                mmq_moe($t, tmp_fixup, x, y, ids_dst, expert_bounds, dst, ncols_x, nrows_x, ncols_dst, stride_row_x, stride_col_dst, num_experts, ncols_max,
                        cc, nsm, smpbo, warp_size, stream)
            }
        }
    )*};
}
mmq_launchers! {
    launch_mmq_gguf_q4_0, launch_mmq_gguf_q4_0_moe, Ty::Q4_0;
    launch_mmq_gguf_q4_1, launch_mmq_gguf_q4_1_moe, Ty::Q4_1;
    launch_mmq_gguf_q5_0, launch_mmq_gguf_q5_0_moe, Ty::Q5_0;
    launch_mmq_gguf_q5_1, launch_mmq_gguf_q5_1_moe, Ty::Q5_1;
    launch_mmq_gguf_q8_0, launch_mmq_gguf_q8_0_moe, Ty::Q8_0;
    launch_mmq_gguf_q2_k, launch_mmq_gguf_q2_k_moe, Ty::Q2K;
    launch_mmq_gguf_q3_k, launch_mmq_gguf_q3_k_moe, Ty::Q3K;
    launch_mmq_gguf_q4_k, launch_mmq_gguf_q4_k_moe, Ty::Q4K;
    launch_mmq_gguf_q5_k, launch_mmq_gguf_q5_k_moe, Ty::Q5K;
    launch_mmq_gguf_q6_k, launch_mmq_gguf_q6_k_moe, Ty::Q6K;
}

/// For the gate: the (mmq_x, stream-k grid) a launcher call picks, so tmp_fixup slots can be
/// mapped to their output tile. `qk` selects the type's shared-memory sizes via its name.
pub fn plan(tname: &str, ncols_max: i64, nrows_x: i64, nchannels: i64, cc: i32, nsm: i32, smpbo: i64) -> Option<(i32, u32)> {
    let t = [Ty::Q4_0, Ty::Q4_1, Ty::Q5_0, Ty::Q5_1, Ty::Q8_0, Ty::Q2K, Ty::Q3K, Ty::Q4K, Ty::Q5K, Ty::Q6K][TYPES.iter().position(|n| *n == tname)?];
    let (mmq_x_max, mmq_y, nwarps) = (if turing_mma_available(cc) { 128 } else { 64 }, 128, 8);
    let (mut best, mut nbest) = (0, i32::MAX);
    let mut x = 8;
    while x <= mmq_x_max && nbest > 1 {
        let gran = if turing_mma_available(cc) && x >= 48 { 16 } else { 8 };
        if x % gran == 0 && nbytes_shared(t, x, mmq_y, cc, 32, nwarps) <= smpbo as u64 {
            let n = ((ncols_max + x as i64 - 1) / x as i64) as i32;
            if n < nbest {
                best = x;
                nbest = n;
            }
        }
        x += 8;
    }
    if best == 0 {
        return None;
    }
    let nty = ((nrows_x + 127) / 128) as i32;
    let ntx = ((ncols_max + best as i64 - 1) / best as i64) as i32;
    let ntiles = ntx * nty * nchannels as i32;
    let waves = (ntiles + nsm - 1) / nsm;
    let eff = 100 * ntiles / (nsm * waves);
    Some((best, if eff >= 90 { ntiles as u32 } else { nsm as u32 }))
}
