#!/usr/bin/env python3
"""Emit the i-quant codebook arrays for candle's iquant.rs from ggml-common.h.

candle needs plain const arrays; the CUDA side keeps its compare chains (a runtime-indexed host
table never reaches the PTX). GGML_TABLE_BEGIN entries are written in mixed hex and *decimal*
(the ksigns/kmask tables are decimal), so parse tokens generically and assert the length.
"""
import re, os

SRC = "~/ai/llama.cpp/ggml/src/ggml-common.h"
DST = "~/titan-engine/candle/candle-core/src/quantized/"
src = open(SRC).read()

TABLES = {
    "iq2xxs_grid": (256, "IQ2XXS_GRID"),
    "iq2s_grid": (1024, "IQ2S_GRID"),
    "iq3xxs_grid": (256, "IQ3XXS_GRID"),
    "iq2xs_grid": (512, "IQ2XS_GRID"),
}


def table(name):
    m = re.search(
        r"GGML_TABLE_BEGIN\([^,]+,\s*" + name + r",\s*(\d+)\)(.*?)GGML_TABLE_END\(\)", src, re.S
    )
    if not m:
        raise SystemExit("table %s not found" % name)
    n = int(m.group(1))
    body = re.sub(r"//[^\n]*", "", m.group(2))
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    vals = [int(t, 0) for t in re.findall(r"(?:0x[0-9a-fA-F]+|\d+)", body)]
    assert len(vals) == n, "%s: expected %d values, parsed %d" % (name, n, len(vals))
    assert all(0 <= v < 2**64 for v in vals), name
    return vals


for name, (count, const) in TABLES.items():
    vals = table(name)
    assert len(vals) == count, (name, len(vals))
    # Every grid byte is 0..=127, so a u64 round-trips as 8 unsigned bytes.
    assert all(b <= 0x7F for v in vals for b in v.to_bytes(8, "little")), name
    out = [
        "// %s[%d] from ggml-common.h; generated by oxide-kernels/gen_iquant_tables.py"
        % (name, count)
    ]
    for i in range(0, len(vals), 4):
        out.append("    " + ", ".join("0x%016x" % v for v in vals[i : i + 4]) + ",")
    # ONE expression: these files are pulled in with include!().
    text = "[\n" + "\n".join(out[1:]) + "\n]"
    path = os.path.join(DST, "data_%s.rs" % name)
    with open(path, "w") as fh:
        fh.write(text + "\n")
    print("%-14s %5d values -> %s (%d bytes)" % (name, count, const, os.path.getsize(path)))
